/*
 * generated by Xtext 2.38.0
 */
package org.thingml.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ThingMLUiModule extends AbstractThingMLUiModule {

	public ThingMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
