/**
 * generated by Xtext 2.38.0
 */
package org.thingml.xtext.thingML.tests;

import junit.textui.TestRunner;

import org.thingml.xtext.thingML.PMML_ModelAlgorithm;
import org.thingml.xtext.thingML.ThingMLFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>PMML Model Algorithm</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class PMML_ModelAlgorithmTest extends DataAnalyticsModelAlgorithmTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(PMML_ModelAlgorithmTest.class);
	}

	/**
	 * Constructs a new PMML Model Algorithm test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public PMML_ModelAlgorithmTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this PMML Model Algorithm test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected PMML_ModelAlgorithm getFixture() {
		return (PMML_ModelAlgorithm)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(ThingMLFactory.eINSTANCE.createPMML_ModelAlgorithm());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //PMML_ModelAlgorithmTest
