/**
 * generated by Xtext 2.38.0
 */
package org.thingml.xtext.thingML.tests;

import junit.textui.TestRunner;

import org.thingml.xtext.thingML.ThingMLFactory;
import org.thingml.xtext.thingML.Time_series_ModelAlgorithm;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Time series Model Algorithm</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class Time_series_ModelAlgorithmTest extends DataAnalyticsModelAlgorithmTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(Time_series_ModelAlgorithmTest.class);
	}

	/**
	 * Constructs a new Time series Model Algorithm test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Time_series_ModelAlgorithmTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Time series Model Algorithm test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected Time_series_ModelAlgorithm getFixture() {
		return (Time_series_ModelAlgorithm)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(ThingMLFactory.eINSTANCE.createTime_series_ModelAlgorithm());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //Time_series_ModelAlgorithmTest
