/*
 * generated by Xtext 2.38.0
 */
package org.thingml.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.thingml.xtext.ThingMLRuntimeModule;
import org.thingml.xtext.ThingMLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ThingMLIdeSetup extends ThingMLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ThingMLRuntimeModule(), new ThingMLIdeModule()));
	}
	
}
