/**
 * generated by Xtext 2.38.0
 */
package org.thingml.xtext.thingML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Event</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.thingml.xtext.thingML.ThingMLPackage#getEvent()
 * @model
 * @generated
 */
public interface Event extends NamedElement
{
} // Event
