/**
 * generated by Xtext 2.38.0
 */
package org.thingml.xtext.thingML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Gaussian Mixture</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.thingml.xtext.thingML.GaussianMixture#getN_components <em>Ncomponents</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.GaussianMixture#getCovariance_type <em>Covariance type</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.GaussianMixture#getTol <em>Tol</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.GaussianMixture#getReg_covar <em>Reg covar</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.GaussianMixture#getMax_iter <em>Max iter</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.GaussianMixture#getN_init <em>Ninit</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.GaussianMixture#getInit_params <em>Init params</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.GaussianMixture#getWeights_init <em>Weights init</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.GaussianMixture#getMeans_init <em>Means init</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.GaussianMixture#getPrecisions_init <em>Precisions init</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.GaussianMixture#getRandom_state <em>Random state</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.GaussianMixture#getWarm_start <em>Warm start</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.GaussianMixture#getVerbose <em>Verbose</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.GaussianMixture#getVerbose_interval <em>Verbose interval</em>}</li>
 * </ul>
 *
 * @see org.thingml.xtext.thingML.ThingMLPackage#getGaussianMixture()
 * @model
 * @generated
 */
public interface GaussianMixture extends ML2_ModelAlgorithm
{
  /**
   * Returns the value of the '<em><b>Ncomponents</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ncomponents</em>' containment reference.
   * @see #setN_components(IntegerLiteral)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getGaussianMixture_N_components()
   * @model containment="true"
   * @generated
   */
  IntegerLiteral getN_components();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.GaussianMixture#getN_components <em>Ncomponents</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ncomponents</em>' containment reference.
   * @see #getN_components()
   * @generated
   */
  void setN_components(IntegerLiteral value);

  /**
   * Returns the value of the '<em><b>Covariance type</b></em>' attribute.
   * The literals are from the enumeration {@link org.thingml.xtext.thingML.Covariance_Type}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Covariance type</em>' attribute.
   * @see org.thingml.xtext.thingML.Covariance_Type
   * @see #setCovariance_type(Covariance_Type)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getGaussianMixture_Covariance_type()
   * @model
   * @generated
   */
  Covariance_Type getCovariance_type();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.GaussianMixture#getCovariance_type <em>Covariance type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Covariance type</em>' attribute.
   * @see org.thingml.xtext.thingML.Covariance_Type
   * @see #getCovariance_type()
   * @generated
   */
  void setCovariance_type(Covariance_Type value);

  /**
   * Returns the value of the '<em><b>Tol</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tol</em>' containment reference.
   * @see #setTol(DoubleLiteral)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getGaussianMixture_Tol()
   * @model containment="true"
   * @generated
   */
  DoubleLiteral getTol();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.GaussianMixture#getTol <em>Tol</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tol</em>' containment reference.
   * @see #getTol()
   * @generated
   */
  void setTol(DoubleLiteral value);

  /**
   * Returns the value of the '<em><b>Reg covar</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reg covar</em>' containment reference.
   * @see #setReg_covar(DoubleLiteral)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getGaussianMixture_Reg_covar()
   * @model containment="true"
   * @generated
   */
  DoubleLiteral getReg_covar();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.GaussianMixture#getReg_covar <em>Reg covar</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reg covar</em>' containment reference.
   * @see #getReg_covar()
   * @generated
   */
  void setReg_covar(DoubleLiteral value);

  /**
   * Returns the value of the '<em><b>Max iter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max iter</em>' containment reference.
   * @see #setMax_iter(IntegerLiteral)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getGaussianMixture_Max_iter()
   * @model containment="true"
   * @generated
   */
  IntegerLiteral getMax_iter();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.GaussianMixture#getMax_iter <em>Max iter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max iter</em>' containment reference.
   * @see #getMax_iter()
   * @generated
   */
  void setMax_iter(IntegerLiteral value);

  /**
   * Returns the value of the '<em><b>Ninit</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ninit</em>' containment reference.
   * @see #setN_init(IntegerLiteral)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getGaussianMixture_N_init()
   * @model containment="true"
   * @generated
   */
  IntegerLiteral getN_init();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.GaussianMixture#getN_init <em>Ninit</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ninit</em>' containment reference.
   * @see #getN_init()
   * @generated
   */
  void setN_init(IntegerLiteral value);

  /**
   * Returns the value of the '<em><b>Init params</b></em>' attribute.
   * The literals are from the enumeration {@link org.thingml.xtext.thingML.Init_Params_Methods}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Init params</em>' attribute.
   * @see org.thingml.xtext.thingML.Init_Params_Methods
   * @see #setInit_params(Init_Params_Methods)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getGaussianMixture_Init_params()
   * @model
   * @generated
   */
  Init_Params_Methods getInit_params();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.GaussianMixture#getInit_params <em>Init params</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Init params</em>' attribute.
   * @see org.thingml.xtext.thingML.Init_Params_Methods
   * @see #getInit_params()
   * @generated
   */
  void setInit_params(Init_Params_Methods value);

  /**
   * Returns the value of the '<em><b>Weights init</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Weights init</em>' attribute.
   * @see #setWeights_init(String)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getGaussianMixture_Weights_init()
   * @model
   * @generated
   */
  String getWeights_init();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.GaussianMixture#getWeights_init <em>Weights init</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Weights init</em>' attribute.
   * @see #getWeights_init()
   * @generated
   */
  void setWeights_init(String value);

  /**
   * Returns the value of the '<em><b>Means init</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Means init</em>' attribute.
   * @see #setMeans_init(String)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getGaussianMixture_Means_init()
   * @model
   * @generated
   */
  String getMeans_init();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.GaussianMixture#getMeans_init <em>Means init</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Means init</em>' attribute.
   * @see #getMeans_init()
   * @generated
   */
  void setMeans_init(String value);

  /**
   * Returns the value of the '<em><b>Precisions init</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Precisions init</em>' attribute.
   * @see #setPrecisions_init(String)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getGaussianMixture_Precisions_init()
   * @model
   * @generated
   */
  String getPrecisions_init();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.GaussianMixture#getPrecisions_init <em>Precisions init</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Precisions init</em>' attribute.
   * @see #getPrecisions_init()
   * @generated
   */
  void setPrecisions_init(String value);

  /**
   * Returns the value of the '<em><b>Random state</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Random state</em>' containment reference.
   * @see #setRandom_state(IntegerLiteral)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getGaussianMixture_Random_state()
   * @model containment="true"
   * @generated
   */
  IntegerLiteral getRandom_state();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.GaussianMixture#getRandom_state <em>Random state</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Random state</em>' containment reference.
   * @see #getRandom_state()
   * @generated
   */
  void setRandom_state(IntegerLiteral value);

  /**
   * Returns the value of the '<em><b>Warm start</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Warm start</em>' containment reference.
   * @see #setWarm_start(BooleanLiteral)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getGaussianMixture_Warm_start()
   * @model containment="true"
   * @generated
   */
  BooleanLiteral getWarm_start();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.GaussianMixture#getWarm_start <em>Warm start</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Warm start</em>' containment reference.
   * @see #getWarm_start()
   * @generated
   */
  void setWarm_start(BooleanLiteral value);

  /**
   * Returns the value of the '<em><b>Verbose</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Verbose</em>' containment reference.
   * @see #setVerbose(IntegerLiteral)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getGaussianMixture_Verbose()
   * @model containment="true"
   * @generated
   */
  IntegerLiteral getVerbose();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.GaussianMixture#getVerbose <em>Verbose</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Verbose</em>' containment reference.
   * @see #getVerbose()
   * @generated
   */
  void setVerbose(IntegerLiteral value);

  /**
   * Returns the value of the '<em><b>Verbose interval</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Verbose interval</em>' containment reference.
   * @see #setVerbose_interval(IntegerLiteral)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getGaussianMixture_Verbose_interval()
   * @model containment="true"
   * @generated
   */
  IntegerLiteral getVerbose_interval();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.GaussianMixture#getVerbose_interval <em>Verbose interval</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Verbose interval</em>' containment reference.
   * @see #getVerbose_interval()
   * @generated
   */
  void setVerbose_interval(IntegerLiteral value);

} // GaussianMixture
