/**
 * generated by Xtext 2.38.0
 */
package org.thingml.xtext.thingML;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Message</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.thingml.xtext.thingML.Message#getParameters <em>Parameters</em>}</li>
 * </ul>
 *
 * @see org.thingml.xtext.thingML.ThingMLPackage#getMessage()
 * @model
 * @generated
 */
public interface Message extends NamedElement, AnnotatedElement, MessageParameter
{
  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link org.thingml.xtext.thingML.Parameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see org.thingml.xtext.thingML.ThingMLPackage#getMessage_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<Parameter> getParameters();

} // Message
