/**
 * generated by Xtext 2.38.0
 */
package org.thingml.xtext.thingML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.thingml.xtext.thingML.ThingMLPackage#getParameter()
 * @model
 * @generated
 */
public interface Parameter extends NamedElement, AnnotatedElement, Variable, MessageParameter
{
} // Parameter
