/**
 * generated by Xtext 2.38.0
 */
package org.thingml.xtext.thingML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PMML Model Algorithm</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.thingml.xtext.thingML.PMML_ModelAlgorithm#getPmml_path <em>Pmml path</em>}</li>
 * </ul>
 *
 * @see org.thingml.xtext.thingML.ThingMLPackage#getPMML_ModelAlgorithm()
 * @model
 * @generated
 */
public interface PMML_ModelAlgorithm extends DataAnalyticsModelAlgorithm
{
  /**
   * Returns the value of the '<em><b>Pmml path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pmml path</em>' attribute.
   * @see #setPmml_path(String)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getPMML_ModelAlgorithm_Pmml_path()
   * @model
   * @generated
   */
  String getPmml_path();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.PMML_ModelAlgorithm#getPmml_path <em>Pmml path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pmml path</em>' attribute.
   * @see #getPmml_path()
   * @generated
   */
  void setPmml_path(String value);

} // PMML_ModelAlgorithm
