/**
 * generated by Xtext 2.38.0
 */
package org.thingml.xtext.thingML;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Preprocess sample normalizer</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.thingml.xtext.thingML.ThingMLPackage#getPreprocess_sample_normalizer()
 * @model
 * @generated
 */
public enum Preprocess_sample_normalizer implements Enumerator
{
  /**
   * The '<em><b>NOT SET</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NOT_SET_VALUE
   * @generated
   * @ordered
   */
  NOT_SET(0, "NOT_SET", "NOT_SET"),

  /**
   * The '<em><b>OFF</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #OFF_VALUE
   * @generated
   * @ordered
   */
  OFF(1, "OFF", "OFF"),

  /**
   * The '<em><b>NORMALIZER L2 NORM</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NORMALIZER_L2_NORM_VALUE
   * @generated
   * @ordered
   */
  NORMALIZER_L2_NORM(2, "NORMALIZER_L2_NORM", "NORMALIZER_L2_NORM"),

  /**
   * The '<em><b>NORMALIZER L1 NORM</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NORMALIZER_L1_NORM_VALUE
   * @generated
   * @ordered
   */
  NORMALIZER_L1_NORM(3, "NORMALIZER_L1_NORM", "NORMALIZER_L1_NORM"),

  /**
   * The '<em><b>NORMALIZER MAX NORM</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NORMALIZER_MAX_NORM_VALUE
   * @generated
   * @ordered
   */
  NORMALIZER_MAX_NORM(4, "NORMALIZER_MAX_NORM", "NORMALIZER_MAX_NORM");

  /**
   * The '<em><b>NOT SET</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NOT_SET
   * @model
   * @generated
   * @ordered
   */
  public static final int NOT_SET_VALUE = 0;

  /**
   * The '<em><b>OFF</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #OFF
   * @model
   * @generated
   * @ordered
   */
  public static final int OFF_VALUE = 1;

  /**
   * The '<em><b>NORMALIZER L2 NORM</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NORMALIZER_L2_NORM
   * @model
   * @generated
   * @ordered
   */
  public static final int NORMALIZER_L2_NORM_VALUE = 2;

  /**
   * The '<em><b>NORMALIZER L1 NORM</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NORMALIZER_L1_NORM
   * @model
   * @generated
   * @ordered
   */
  public static final int NORMALIZER_L1_NORM_VALUE = 3;

  /**
   * The '<em><b>NORMALIZER MAX NORM</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NORMALIZER_MAX_NORM
   * @model
   * @generated
   * @ordered
   */
  public static final int NORMALIZER_MAX_NORM_VALUE = 4;

  /**
   * An array of all the '<em><b>Preprocess sample normalizer</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final Preprocess_sample_normalizer[] VALUES_ARRAY =
    new Preprocess_sample_normalizer[]
    {
      NOT_SET,
      OFF,
      NORMALIZER_L2_NORM,
      NORMALIZER_L1_NORM,
      NORMALIZER_MAX_NORM,
    };

  /**
   * A public read-only list of all the '<em><b>Preprocess sample normalizer</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<Preprocess_sample_normalizer> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Preprocess sample normalizer</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Preprocess_sample_normalizer get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Preprocess_sample_normalizer result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Preprocess sample normalizer</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Preprocess_sample_normalizer getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Preprocess_sample_normalizer result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Preprocess sample normalizer</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Preprocess_sample_normalizer get(int value)
  {
    switch (value)
    {
      case NOT_SET_VALUE: return NOT_SET;
      case OFF_VALUE: return OFF;
      case NORMALIZER_L2_NORM_VALUE: return NORMALIZER_L2_NORM;
      case NORMALIZER_L1_NORM_VALUE: return NORMALIZER_L1_NORM;
      case NORMALIZER_MAX_NORM_VALUE: return NORMALIZER_MAX_NORM;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private Preprocess_sample_normalizer(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //Preprocess_sample_normalizer
