/**
 * generated by Xtext 2.38.0
 */
package org.thingml.xtext.thingML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SVR</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.thingml.xtext.thingML.SVR#getKernel <em>Kernel</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.SVR#getDegree <em>Degree</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.SVR#getGamma <em>Gamma</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.SVR#getCoef0 <em>Coef0</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.SVR#getTol <em>Tol</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.SVR#getC <em>C</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.SVR#getEpsilon <em>Epsilon</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.SVR#getShrinking <em>Shrinking</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.SVR#getCache_size <em>Cache size</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.SVR#getVerbose <em>Verbose</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.SVR#getMax_iter <em>Max iter</em>}</li>
 * </ul>
 *
 * @see org.thingml.xtext.thingML.ThingMLPackage#getSVR()
 * @model
 * @generated
 */
public interface SVR extends machine_learning_ModelAlgorithm
{
  /**
   * Returns the value of the '<em><b>Kernel</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Kernel</em>' attribute.
   * @see #setKernel(String)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getSVR_Kernel()
   * @model
   * @generated
   */
  String getKernel();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.SVR#getKernel <em>Kernel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Kernel</em>' attribute.
   * @see #getKernel()
   * @generated
   */
  void setKernel(String value);

  /**
   * Returns the value of the '<em><b>Degree</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Degree</em>' containment reference.
   * @see #setDegree(IntegerLiteral)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getSVR_Degree()
   * @model containment="true"
   * @generated
   */
  IntegerLiteral getDegree();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.SVR#getDegree <em>Degree</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Degree</em>' containment reference.
   * @see #getDegree()
   * @generated
   */
  void setDegree(IntegerLiteral value);

  /**
   * Returns the value of the '<em><b>Gamma</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gamma</em>' attribute.
   * @see #setGamma(String)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getSVR_Gamma()
   * @model
   * @generated
   */
  String getGamma();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.SVR#getGamma <em>Gamma</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gamma</em>' attribute.
   * @see #getGamma()
   * @generated
   */
  void setGamma(String value);

  /**
   * Returns the value of the '<em><b>Coef0</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Coef0</em>' attribute.
   * @see #setCoef0(double)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getSVR_Coef0()
   * @model
   * @generated
   */
  double getCoef0();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.SVR#getCoef0 <em>Coef0</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Coef0</em>' attribute.
   * @see #getCoef0()
   * @generated
   */
  void setCoef0(double value);

  /**
   * Returns the value of the '<em><b>Tol</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tol</em>' attribute.
   * @see #setTol(double)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getSVR_Tol()
   * @model
   * @generated
   */
  double getTol();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.SVR#getTol <em>Tol</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tol</em>' attribute.
   * @see #getTol()
   * @generated
   */
  void setTol(double value);

  /**
   * Returns the value of the '<em><b>C</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>C</em>' attribute.
   * @see #setC(double)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getSVR_C()
   * @model
   * @generated
   */
  double getC();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.SVR#getC <em>C</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>C</em>' attribute.
   * @see #getC()
   * @generated
   */
  void setC(double value);

  /**
   * Returns the value of the '<em><b>Epsilon</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Epsilon</em>' attribute.
   * @see #setEpsilon(double)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getSVR_Epsilon()
   * @model
   * @generated
   */
  double getEpsilon();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.SVR#getEpsilon <em>Epsilon</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Epsilon</em>' attribute.
   * @see #getEpsilon()
   * @generated
   */
  void setEpsilon(double value);

  /**
   * Returns the value of the '<em><b>Shrinking</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Shrinking</em>' containment reference.
   * @see #setShrinking(BooleanLiteral)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getSVR_Shrinking()
   * @model containment="true"
   * @generated
   */
  BooleanLiteral getShrinking();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.SVR#getShrinking <em>Shrinking</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Shrinking</em>' containment reference.
   * @see #getShrinking()
   * @generated
   */
  void setShrinking(BooleanLiteral value);

  /**
   * Returns the value of the '<em><b>Cache size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cache size</em>' attribute.
   * @see #setCache_size(double)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getSVR_Cache_size()
   * @model
   * @generated
   */
  double getCache_size();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.SVR#getCache_size <em>Cache size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cache size</em>' attribute.
   * @see #getCache_size()
   * @generated
   */
  void setCache_size(double value);

  /**
   * Returns the value of the '<em><b>Verbose</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Verbose</em>' containment reference.
   * @see #setVerbose(BooleanLiteral)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getSVR_Verbose()
   * @model containment="true"
   * @generated
   */
  BooleanLiteral getVerbose();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.SVR#getVerbose <em>Verbose</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Verbose</em>' containment reference.
   * @see #getVerbose()
   * @generated
   */
  void setVerbose(BooleanLiteral value);

  /**
   * Returns the value of the '<em><b>Max iter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max iter</em>' containment reference.
   * @see #setMax_iter(IntegerLiteral)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getSVR_Max_iter()
   * @model containment="true"
   * @generated
   */
  IntegerLiteral getMax_iter();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.SVR#getMax_iter <em>Max iter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max iter</em>' containment reference.
   * @see #getMax_iter()
   * @generated
   */
  void setMax_iter(IntegerLiteral value);

} // SVR
