/**
 * generated by Xtext 2.38.0
 */
package org.thingml.xtext.thingML.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.thingml.xtext.thingML.BooleanLiteral;
import org.thingml.xtext.thingML.ClassifierWithPredictionCertaintyProbabilities;
import org.thingml.xtext.thingML.DoubleLiteral;
import org.thingml.xtext.thingML.IntegerLiteral;
import org.thingml.xtext.thingML.SelfTrainingClassifier;
import org.thingml.xtext.thingML.Self_Training_Criterion;
import org.thingml.xtext.thingML.ThingMLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Self Training Classifier</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.thingml.xtext.thingML.impl.SelfTrainingClassifierImpl#getBase_estimator <em>Base estimator</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.SelfTrainingClassifierImpl#getThreshold <em>Threshold</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.SelfTrainingClassifierImpl#getCriterion <em>Criterion</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.SelfTrainingClassifierImpl#getK_best <em>Kbest</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.SelfTrainingClassifierImpl#getMax_iter <em>Max iter</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.SelfTrainingClassifierImpl#getVerbose <em>Verbose</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SelfTrainingClassifierImpl extends ML2_ModelAlgorithmImpl implements SelfTrainingClassifier
{
  /**
   * The cached value of the '{@link #getBase_estimator() <em>Base estimator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBase_estimator()
   * @generated
   * @ordered
   */
  protected ClassifierWithPredictionCertaintyProbabilities base_estimator;

  /**
   * The cached value of the '{@link #getThreshold() <em>Threshold</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getThreshold()
   * @generated
   * @ordered
   */
  protected DoubleLiteral threshold;

  /**
   * The default value of the '{@link #getCriterion() <em>Criterion</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCriterion()
   * @generated
   * @ordered
   */
  protected static final Self_Training_Criterion CRITERION_EDEFAULT = Self_Training_Criterion.NOT_SET;

  /**
   * The cached value of the '{@link #getCriterion() <em>Criterion</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCriterion()
   * @generated
   * @ordered
   */
  protected Self_Training_Criterion criterion = CRITERION_EDEFAULT;

  /**
   * The cached value of the '{@link #getK_best() <em>Kbest</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getK_best()
   * @generated
   * @ordered
   */
  protected IntegerLiteral k_best;

  /**
   * The cached value of the '{@link #getMax_iter() <em>Max iter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMax_iter()
   * @generated
   * @ordered
   */
  protected IntegerLiteral max_iter;

  /**
   * The cached value of the '{@link #getVerbose() <em>Verbose</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVerbose()
   * @generated
   * @ordered
   */
  protected BooleanLiteral verbose;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SelfTrainingClassifierImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ThingMLPackage.eINSTANCE.getSelfTrainingClassifier();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ClassifierWithPredictionCertaintyProbabilities getBase_estimator()
  {
    return base_estimator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetBase_estimator(ClassifierWithPredictionCertaintyProbabilities newBase_estimator, NotificationChain msgs)
  {
    ClassifierWithPredictionCertaintyProbabilities oldBase_estimator = base_estimator;
    base_estimator = newBase_estimator;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.SELF_TRAINING_CLASSIFIER__BASE_ESTIMATOR, oldBase_estimator, newBase_estimator);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setBase_estimator(ClassifierWithPredictionCertaintyProbabilities newBase_estimator)
  {
    if (newBase_estimator != base_estimator)
    {
      NotificationChain msgs = null;
      if (base_estimator != null)
        msgs = ((InternalEObject)base_estimator).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.SELF_TRAINING_CLASSIFIER__BASE_ESTIMATOR, null, msgs);
      if (newBase_estimator != null)
        msgs = ((InternalEObject)newBase_estimator).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.SELF_TRAINING_CLASSIFIER__BASE_ESTIMATOR, null, msgs);
      msgs = basicSetBase_estimator(newBase_estimator, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.SELF_TRAINING_CLASSIFIER__BASE_ESTIMATOR, newBase_estimator, newBase_estimator));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DoubleLiteral getThreshold()
  {
    return threshold;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetThreshold(DoubleLiteral newThreshold, NotificationChain msgs)
  {
    DoubleLiteral oldThreshold = threshold;
    threshold = newThreshold;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.SELF_TRAINING_CLASSIFIER__THRESHOLD, oldThreshold, newThreshold);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setThreshold(DoubleLiteral newThreshold)
  {
    if (newThreshold != threshold)
    {
      NotificationChain msgs = null;
      if (threshold != null)
        msgs = ((InternalEObject)threshold).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.SELF_TRAINING_CLASSIFIER__THRESHOLD, null, msgs);
      if (newThreshold != null)
        msgs = ((InternalEObject)newThreshold).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.SELF_TRAINING_CLASSIFIER__THRESHOLD, null, msgs);
      msgs = basicSetThreshold(newThreshold, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.SELF_TRAINING_CLASSIFIER__THRESHOLD, newThreshold, newThreshold));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Self_Training_Criterion getCriterion()
  {
    return criterion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCriterion(Self_Training_Criterion newCriterion)
  {
    Self_Training_Criterion oldCriterion = criterion;
    criterion = newCriterion == null ? CRITERION_EDEFAULT : newCriterion;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.SELF_TRAINING_CLASSIFIER__CRITERION, oldCriterion, criterion));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegerLiteral getK_best()
  {
    return k_best;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetK_best(IntegerLiteral newK_best, NotificationChain msgs)
  {
    IntegerLiteral oldK_best = k_best;
    k_best = newK_best;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.SELF_TRAINING_CLASSIFIER__KBEST, oldK_best, newK_best);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setK_best(IntegerLiteral newK_best)
  {
    if (newK_best != k_best)
    {
      NotificationChain msgs = null;
      if (k_best != null)
        msgs = ((InternalEObject)k_best).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.SELF_TRAINING_CLASSIFIER__KBEST, null, msgs);
      if (newK_best != null)
        msgs = ((InternalEObject)newK_best).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.SELF_TRAINING_CLASSIFIER__KBEST, null, msgs);
      msgs = basicSetK_best(newK_best, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.SELF_TRAINING_CLASSIFIER__KBEST, newK_best, newK_best));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegerLiteral getMax_iter()
  {
    return max_iter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetMax_iter(IntegerLiteral newMax_iter, NotificationChain msgs)
  {
    IntegerLiteral oldMax_iter = max_iter;
    max_iter = newMax_iter;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.SELF_TRAINING_CLASSIFIER__MAX_ITER, oldMax_iter, newMax_iter);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMax_iter(IntegerLiteral newMax_iter)
  {
    if (newMax_iter != max_iter)
    {
      NotificationChain msgs = null;
      if (max_iter != null)
        msgs = ((InternalEObject)max_iter).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.SELF_TRAINING_CLASSIFIER__MAX_ITER, null, msgs);
      if (newMax_iter != null)
        msgs = ((InternalEObject)newMax_iter).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.SELF_TRAINING_CLASSIFIER__MAX_ITER, null, msgs);
      msgs = basicSetMax_iter(newMax_iter, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.SELF_TRAINING_CLASSIFIER__MAX_ITER, newMax_iter, newMax_iter));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BooleanLiteral getVerbose()
  {
    return verbose;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetVerbose(BooleanLiteral newVerbose, NotificationChain msgs)
  {
    BooleanLiteral oldVerbose = verbose;
    verbose = newVerbose;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.SELF_TRAINING_CLASSIFIER__VERBOSE, oldVerbose, newVerbose);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVerbose(BooleanLiteral newVerbose)
  {
    if (newVerbose != verbose)
    {
      NotificationChain msgs = null;
      if (verbose != null)
        msgs = ((InternalEObject)verbose).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.SELF_TRAINING_CLASSIFIER__VERBOSE, null, msgs);
      if (newVerbose != null)
        msgs = ((InternalEObject)newVerbose).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.SELF_TRAINING_CLASSIFIER__VERBOSE, null, msgs);
      msgs = basicSetVerbose(newVerbose, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.SELF_TRAINING_CLASSIFIER__VERBOSE, newVerbose, newVerbose));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ThingMLPackage.SELF_TRAINING_CLASSIFIER__BASE_ESTIMATOR:
        return basicSetBase_estimator(null, msgs);
      case ThingMLPackage.SELF_TRAINING_CLASSIFIER__THRESHOLD:
        return basicSetThreshold(null, msgs);
      case ThingMLPackage.SELF_TRAINING_CLASSIFIER__KBEST:
        return basicSetK_best(null, msgs);
      case ThingMLPackage.SELF_TRAINING_CLASSIFIER__MAX_ITER:
        return basicSetMax_iter(null, msgs);
      case ThingMLPackage.SELF_TRAINING_CLASSIFIER__VERBOSE:
        return basicSetVerbose(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ThingMLPackage.SELF_TRAINING_CLASSIFIER__BASE_ESTIMATOR:
        return getBase_estimator();
      case ThingMLPackage.SELF_TRAINING_CLASSIFIER__THRESHOLD:
        return getThreshold();
      case ThingMLPackage.SELF_TRAINING_CLASSIFIER__CRITERION:
        return getCriterion();
      case ThingMLPackage.SELF_TRAINING_CLASSIFIER__KBEST:
        return getK_best();
      case ThingMLPackage.SELF_TRAINING_CLASSIFIER__MAX_ITER:
        return getMax_iter();
      case ThingMLPackage.SELF_TRAINING_CLASSIFIER__VERBOSE:
        return getVerbose();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ThingMLPackage.SELF_TRAINING_CLASSIFIER__BASE_ESTIMATOR:
        setBase_estimator((ClassifierWithPredictionCertaintyProbabilities)newValue);
        return;
      case ThingMLPackage.SELF_TRAINING_CLASSIFIER__THRESHOLD:
        setThreshold((DoubleLiteral)newValue);
        return;
      case ThingMLPackage.SELF_TRAINING_CLASSIFIER__CRITERION:
        setCriterion((Self_Training_Criterion)newValue);
        return;
      case ThingMLPackage.SELF_TRAINING_CLASSIFIER__KBEST:
        setK_best((IntegerLiteral)newValue);
        return;
      case ThingMLPackage.SELF_TRAINING_CLASSIFIER__MAX_ITER:
        setMax_iter((IntegerLiteral)newValue);
        return;
      case ThingMLPackage.SELF_TRAINING_CLASSIFIER__VERBOSE:
        setVerbose((BooleanLiteral)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ThingMLPackage.SELF_TRAINING_CLASSIFIER__BASE_ESTIMATOR:
        setBase_estimator((ClassifierWithPredictionCertaintyProbabilities)null);
        return;
      case ThingMLPackage.SELF_TRAINING_CLASSIFIER__THRESHOLD:
        setThreshold((DoubleLiteral)null);
        return;
      case ThingMLPackage.SELF_TRAINING_CLASSIFIER__CRITERION:
        setCriterion(CRITERION_EDEFAULT);
        return;
      case ThingMLPackage.SELF_TRAINING_CLASSIFIER__KBEST:
        setK_best((IntegerLiteral)null);
        return;
      case ThingMLPackage.SELF_TRAINING_CLASSIFIER__MAX_ITER:
        setMax_iter((IntegerLiteral)null);
        return;
      case ThingMLPackage.SELF_TRAINING_CLASSIFIER__VERBOSE:
        setVerbose((BooleanLiteral)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ThingMLPackage.SELF_TRAINING_CLASSIFIER__BASE_ESTIMATOR:
        return base_estimator != null;
      case ThingMLPackage.SELF_TRAINING_CLASSIFIER__THRESHOLD:
        return threshold != null;
      case ThingMLPackage.SELF_TRAINING_CLASSIFIER__CRITERION:
        return criterion != CRITERION_EDEFAULT;
      case ThingMLPackage.SELF_TRAINING_CLASSIFIER__KBEST:
        return k_best != null;
      case ThingMLPackage.SELF_TRAINING_CLASSIFIER__MAX_ITER:
        return max_iter != null;
      case ThingMLPackage.SELF_TRAINING_CLASSIFIER__VERBOSE:
        return verbose != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (criterion: ");
    result.append(criterion);
    result.append(')');
    return result.toString();
  }

} //SelfTrainingClassifierImpl
