/**
 * generated by Xtext 2.38.0
 */
package org.thingml.xtext.thingML.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.thingml.xtext.thingML.BooleanLiteral;
import org.thingml.xtext.thingML.IntegerLiteral;
import org.thingml.xtext.thingML.SVR;
import org.thingml.xtext.thingML.ThingMLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>SVR</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.thingml.xtext.thingML.impl.SVRImpl#getKernel <em>Kernel</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.SVRImpl#getDegree <em>Degree</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.SVRImpl#getGamma <em>Gamma</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.SVRImpl#getCoef0 <em>Coef0</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.SVRImpl#getTol <em>Tol</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.SVRImpl#getC <em>C</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.SVRImpl#getEpsilon <em>Epsilon</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.SVRImpl#getShrinking <em>Shrinking</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.SVRImpl#getCache_size <em>Cache size</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.SVRImpl#getVerbose <em>Verbose</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.SVRImpl#getMax_iter <em>Max iter</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SVRImpl extends machine_learning_ModelAlgorithmImpl implements SVR
{
  /**
   * The default value of the '{@link #getKernel() <em>Kernel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getKernel()
   * @generated
   * @ordered
   */
  protected static final String KERNEL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getKernel() <em>Kernel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getKernel()
   * @generated
   * @ordered
   */
  protected String kernel = KERNEL_EDEFAULT;

  /**
   * The cached value of the '{@link #getDegree() <em>Degree</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDegree()
   * @generated
   * @ordered
   */
  protected IntegerLiteral degree;

  /**
   * The default value of the '{@link #getGamma() <em>Gamma</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGamma()
   * @generated
   * @ordered
   */
  protected static final String GAMMA_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getGamma() <em>Gamma</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGamma()
   * @generated
   * @ordered
   */
  protected String gamma = GAMMA_EDEFAULT;

  /**
   * The default value of the '{@link #getCoef0() <em>Coef0</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCoef0()
   * @generated
   * @ordered
   */
  protected static final double COEF0_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getCoef0() <em>Coef0</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCoef0()
   * @generated
   * @ordered
   */
  protected double coef0 = COEF0_EDEFAULT;

  /**
   * The default value of the '{@link #getTol() <em>Tol</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTol()
   * @generated
   * @ordered
   */
  protected static final double TOL_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getTol() <em>Tol</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTol()
   * @generated
   * @ordered
   */
  protected double tol = TOL_EDEFAULT;

  /**
   * The default value of the '{@link #getC() <em>C</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getC()
   * @generated
   * @ordered
   */
  protected static final double C_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getC() <em>C</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getC()
   * @generated
   * @ordered
   */
  protected double c = C_EDEFAULT;

  /**
   * The default value of the '{@link #getEpsilon() <em>Epsilon</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEpsilon()
   * @generated
   * @ordered
   */
  protected static final double EPSILON_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getEpsilon() <em>Epsilon</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEpsilon()
   * @generated
   * @ordered
   */
  protected double epsilon = EPSILON_EDEFAULT;

  /**
   * The cached value of the '{@link #getShrinking() <em>Shrinking</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShrinking()
   * @generated
   * @ordered
   */
  protected BooleanLiteral shrinking;

  /**
   * The default value of the '{@link #getCache_size() <em>Cache size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCache_size()
   * @generated
   * @ordered
   */
  protected static final double CACHE_SIZE_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getCache_size() <em>Cache size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCache_size()
   * @generated
   * @ordered
   */
  protected double cache_size = CACHE_SIZE_EDEFAULT;

  /**
   * The cached value of the '{@link #getVerbose() <em>Verbose</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVerbose()
   * @generated
   * @ordered
   */
  protected BooleanLiteral verbose;

  /**
   * The cached value of the '{@link #getMax_iter() <em>Max iter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMax_iter()
   * @generated
   * @ordered
   */
  protected IntegerLiteral max_iter;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SVRImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ThingMLPackage.eINSTANCE.getSVR();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getKernel()
  {
    return kernel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setKernel(String newKernel)
  {
    String oldKernel = kernel;
    kernel = newKernel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.SVR__KERNEL, oldKernel, kernel));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegerLiteral getDegree()
  {
    return degree;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDegree(IntegerLiteral newDegree, NotificationChain msgs)
  {
    IntegerLiteral oldDegree = degree;
    degree = newDegree;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.SVR__DEGREE, oldDegree, newDegree);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDegree(IntegerLiteral newDegree)
  {
    if (newDegree != degree)
    {
      NotificationChain msgs = null;
      if (degree != null)
        msgs = ((InternalEObject)degree).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.SVR__DEGREE, null, msgs);
      if (newDegree != null)
        msgs = ((InternalEObject)newDegree).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.SVR__DEGREE, null, msgs);
      msgs = basicSetDegree(newDegree, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.SVR__DEGREE, newDegree, newDegree));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getGamma()
  {
    return gamma;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setGamma(String newGamma)
  {
    String oldGamma = gamma;
    gamma = newGamma;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.SVR__GAMMA, oldGamma, gamma));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public double getCoef0()
  {
    return coef0;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCoef0(double newCoef0)
  {
    double oldCoef0 = coef0;
    coef0 = newCoef0;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.SVR__COEF0, oldCoef0, coef0));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public double getTol()
  {
    return tol;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTol(double newTol)
  {
    double oldTol = tol;
    tol = newTol;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.SVR__TOL, oldTol, tol));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public double getC()
  {
    return c;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setC(double newC)
  {
    double oldC = c;
    c = newC;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.SVR__C, oldC, c));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public double getEpsilon()
  {
    return epsilon;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEpsilon(double newEpsilon)
  {
    double oldEpsilon = epsilon;
    epsilon = newEpsilon;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.SVR__EPSILON, oldEpsilon, epsilon));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BooleanLiteral getShrinking()
  {
    return shrinking;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetShrinking(BooleanLiteral newShrinking, NotificationChain msgs)
  {
    BooleanLiteral oldShrinking = shrinking;
    shrinking = newShrinking;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.SVR__SHRINKING, oldShrinking, newShrinking);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setShrinking(BooleanLiteral newShrinking)
  {
    if (newShrinking != shrinking)
    {
      NotificationChain msgs = null;
      if (shrinking != null)
        msgs = ((InternalEObject)shrinking).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.SVR__SHRINKING, null, msgs);
      if (newShrinking != null)
        msgs = ((InternalEObject)newShrinking).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.SVR__SHRINKING, null, msgs);
      msgs = basicSetShrinking(newShrinking, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.SVR__SHRINKING, newShrinking, newShrinking));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public double getCache_size()
  {
    return cache_size;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCache_size(double newCache_size)
  {
    double oldCache_size = cache_size;
    cache_size = newCache_size;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.SVR__CACHE_SIZE, oldCache_size, cache_size));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BooleanLiteral getVerbose()
  {
    return verbose;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetVerbose(BooleanLiteral newVerbose, NotificationChain msgs)
  {
    BooleanLiteral oldVerbose = verbose;
    verbose = newVerbose;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.SVR__VERBOSE, oldVerbose, newVerbose);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVerbose(BooleanLiteral newVerbose)
  {
    if (newVerbose != verbose)
    {
      NotificationChain msgs = null;
      if (verbose != null)
        msgs = ((InternalEObject)verbose).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.SVR__VERBOSE, null, msgs);
      if (newVerbose != null)
        msgs = ((InternalEObject)newVerbose).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.SVR__VERBOSE, null, msgs);
      msgs = basicSetVerbose(newVerbose, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.SVR__VERBOSE, newVerbose, newVerbose));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegerLiteral getMax_iter()
  {
    return max_iter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetMax_iter(IntegerLiteral newMax_iter, NotificationChain msgs)
  {
    IntegerLiteral oldMax_iter = max_iter;
    max_iter = newMax_iter;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.SVR__MAX_ITER, oldMax_iter, newMax_iter);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMax_iter(IntegerLiteral newMax_iter)
  {
    if (newMax_iter != max_iter)
    {
      NotificationChain msgs = null;
      if (max_iter != null)
        msgs = ((InternalEObject)max_iter).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.SVR__MAX_ITER, null, msgs);
      if (newMax_iter != null)
        msgs = ((InternalEObject)newMax_iter).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.SVR__MAX_ITER, null, msgs);
      msgs = basicSetMax_iter(newMax_iter, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.SVR__MAX_ITER, newMax_iter, newMax_iter));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ThingMLPackage.SVR__DEGREE:
        return basicSetDegree(null, msgs);
      case ThingMLPackage.SVR__SHRINKING:
        return basicSetShrinking(null, msgs);
      case ThingMLPackage.SVR__VERBOSE:
        return basicSetVerbose(null, msgs);
      case ThingMLPackage.SVR__MAX_ITER:
        return basicSetMax_iter(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ThingMLPackage.SVR__KERNEL:
        return getKernel();
      case ThingMLPackage.SVR__DEGREE:
        return getDegree();
      case ThingMLPackage.SVR__GAMMA:
        return getGamma();
      case ThingMLPackage.SVR__COEF0:
        return getCoef0();
      case ThingMLPackage.SVR__TOL:
        return getTol();
      case ThingMLPackage.SVR__C:
        return getC();
      case ThingMLPackage.SVR__EPSILON:
        return getEpsilon();
      case ThingMLPackage.SVR__SHRINKING:
        return getShrinking();
      case ThingMLPackage.SVR__CACHE_SIZE:
        return getCache_size();
      case ThingMLPackage.SVR__VERBOSE:
        return getVerbose();
      case ThingMLPackage.SVR__MAX_ITER:
        return getMax_iter();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ThingMLPackage.SVR__KERNEL:
        setKernel((String)newValue);
        return;
      case ThingMLPackage.SVR__DEGREE:
        setDegree((IntegerLiteral)newValue);
        return;
      case ThingMLPackage.SVR__GAMMA:
        setGamma((String)newValue);
        return;
      case ThingMLPackage.SVR__COEF0:
        setCoef0((Double)newValue);
        return;
      case ThingMLPackage.SVR__TOL:
        setTol((Double)newValue);
        return;
      case ThingMLPackage.SVR__C:
        setC((Double)newValue);
        return;
      case ThingMLPackage.SVR__EPSILON:
        setEpsilon((Double)newValue);
        return;
      case ThingMLPackage.SVR__SHRINKING:
        setShrinking((BooleanLiteral)newValue);
        return;
      case ThingMLPackage.SVR__CACHE_SIZE:
        setCache_size((Double)newValue);
        return;
      case ThingMLPackage.SVR__VERBOSE:
        setVerbose((BooleanLiteral)newValue);
        return;
      case ThingMLPackage.SVR__MAX_ITER:
        setMax_iter((IntegerLiteral)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ThingMLPackage.SVR__KERNEL:
        setKernel(KERNEL_EDEFAULT);
        return;
      case ThingMLPackage.SVR__DEGREE:
        setDegree((IntegerLiteral)null);
        return;
      case ThingMLPackage.SVR__GAMMA:
        setGamma(GAMMA_EDEFAULT);
        return;
      case ThingMLPackage.SVR__COEF0:
        setCoef0(COEF0_EDEFAULT);
        return;
      case ThingMLPackage.SVR__TOL:
        setTol(TOL_EDEFAULT);
        return;
      case ThingMLPackage.SVR__C:
        setC(C_EDEFAULT);
        return;
      case ThingMLPackage.SVR__EPSILON:
        setEpsilon(EPSILON_EDEFAULT);
        return;
      case ThingMLPackage.SVR__SHRINKING:
        setShrinking((BooleanLiteral)null);
        return;
      case ThingMLPackage.SVR__CACHE_SIZE:
        setCache_size(CACHE_SIZE_EDEFAULT);
        return;
      case ThingMLPackage.SVR__VERBOSE:
        setVerbose((BooleanLiteral)null);
        return;
      case ThingMLPackage.SVR__MAX_ITER:
        setMax_iter((IntegerLiteral)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ThingMLPackage.SVR__KERNEL:
        return KERNEL_EDEFAULT == null ? kernel != null : !KERNEL_EDEFAULT.equals(kernel);
      case ThingMLPackage.SVR__DEGREE:
        return degree != null;
      case ThingMLPackage.SVR__GAMMA:
        return GAMMA_EDEFAULT == null ? gamma != null : !GAMMA_EDEFAULT.equals(gamma);
      case ThingMLPackage.SVR__COEF0:
        return coef0 != COEF0_EDEFAULT;
      case ThingMLPackage.SVR__TOL:
        return tol != TOL_EDEFAULT;
      case ThingMLPackage.SVR__C:
        return c != C_EDEFAULT;
      case ThingMLPackage.SVR__EPSILON:
        return epsilon != EPSILON_EDEFAULT;
      case ThingMLPackage.SVR__SHRINKING:
        return shrinking != null;
      case ThingMLPackage.SVR__CACHE_SIZE:
        return cache_size != CACHE_SIZE_EDEFAULT;
      case ThingMLPackage.SVR__VERBOSE:
        return verbose != null;
      case ThingMLPackage.SVR__MAX_ITER:
        return max_iter != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (kernel: ");
    result.append(kernel);
    result.append(", gamma: ");
    result.append(gamma);
    result.append(", coef0: ");
    result.append(coef0);
    result.append(", tol: ");
    result.append(tol);
    result.append(", C: ");
    result.append(c);
    result.append(", epsilon: ");
    result.append(epsilon);
    result.append(", cache_size: ");
    result.append(cache_size);
    result.append(')');
    return result.toString();
  }

} //SVRImpl
