/**
 * generated by Xtext 2.38.0
 */
package org.thingml.xtext.thingML.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.thingml.xtext.thingML.Activation;
import org.thingml.xtext.thingML.IntegerLiteral;
import org.thingml.xtext.thingML.Loss;
import org.thingml.xtext.thingML.TCN;
import org.thingml.xtext.thingML.ThingMLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>TCN</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.thingml.xtext.thingML.impl.TCNImpl#getHidden_layers <em>Hidden layers</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.TCNImpl#getUnits <em>Units</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.TCNImpl#getNb_filters <em>Nb filters</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.TCNImpl#getKernel_size <em>Kernel size</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.TCNImpl#getDilations <em>Dilations</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.TCNImpl#getNb_stacks <em>Nb stacks</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.TCNImpl#getDropout_rate <em>Dropout rate</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.TCNImpl#getActivation <em>Activation</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.TCNImpl#getLearning_rate <em>Learning rate</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.TCNImpl#getLoss <em>Loss</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.TCNImpl#getDense_layers <em>Dense layers</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.TCNImpl#getNeurons <em>Neurons</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TCNImpl extends Deep_learning_ModelAlgorithmImpl implements TCN
{
  /**
   * The default value of the '{@link #getHidden_layers() <em>Hidden layers</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHidden_layers()
   * @generated
   * @ordered
   */
  protected static final String HIDDEN_LAYERS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getHidden_layers() <em>Hidden layers</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHidden_layers()
   * @generated
   * @ordered
   */
  protected String hidden_layers = HIDDEN_LAYERS_EDEFAULT;

  /**
   * The cached value of the '{@link #getUnits() <em>Units</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUnits()
   * @generated
   * @ordered
   */
  protected EList<IntegerLiteral> units;

  /**
   * The cached value of the '{@link #getNb_filters() <em>Nb filters</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNb_filters()
   * @generated
   * @ordered
   */
  protected IntegerLiteral nb_filters;

  /**
   * The cached value of the '{@link #getKernel_size() <em>Kernel size</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getKernel_size()
   * @generated
   * @ordered
   */
  protected IntegerLiteral kernel_size;

  /**
   * The default value of the '{@link #getDilations() <em>Dilations</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDilations()
   * @generated
   * @ordered
   */
  protected static final String DILATIONS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDilations() <em>Dilations</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDilations()
   * @generated
   * @ordered
   */
  protected String dilations = DILATIONS_EDEFAULT;

  /**
   * The cached value of the '{@link #getNb_stacks() <em>Nb stacks</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNb_stacks()
   * @generated
   * @ordered
   */
  protected IntegerLiteral nb_stacks;

  /**
   * The default value of the '{@link #getDropout_rate() <em>Dropout rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDropout_rate()
   * @generated
   * @ordered
   */
  protected static final double DROPOUT_RATE_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getDropout_rate() <em>Dropout rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDropout_rate()
   * @generated
   * @ordered
   */
  protected double dropout_rate = DROPOUT_RATE_EDEFAULT;

  /**
   * The default value of the '{@link #getActivation() <em>Activation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getActivation()
   * @generated
   * @ordered
   */
  protected static final Activation ACTIVATION_EDEFAULT = Activation.NOT_SET;

  /**
   * The cached value of the '{@link #getActivation() <em>Activation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getActivation()
   * @generated
   * @ordered
   */
  protected Activation activation = ACTIVATION_EDEFAULT;

  /**
   * The default value of the '{@link #getLearning_rate() <em>Learning rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLearning_rate()
   * @generated
   * @ordered
   */
  protected static final double LEARNING_RATE_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getLearning_rate() <em>Learning rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLearning_rate()
   * @generated
   * @ordered
   */
  protected double learning_rate = LEARNING_RATE_EDEFAULT;

  /**
   * The default value of the '{@link #getLoss() <em>Loss</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLoss()
   * @generated
   * @ordered
   */
  protected static final Loss LOSS_EDEFAULT = Loss.NOT_SET;

  /**
   * The cached value of the '{@link #getLoss() <em>Loss</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLoss()
   * @generated
   * @ordered
   */
  protected Loss loss = LOSS_EDEFAULT;

  /**
   * The default value of the '{@link #getDense_layers() <em>Dense layers</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDense_layers()
   * @generated
   * @ordered
   */
  protected static final String DENSE_LAYERS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDense_layers() <em>Dense layers</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDense_layers()
   * @generated
   * @ordered
   */
  protected String dense_layers = DENSE_LAYERS_EDEFAULT;

  /**
   * The cached value of the '{@link #getNeurons() <em>Neurons</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNeurons()
   * @generated
   * @ordered
   */
  protected EList<IntegerLiteral> neurons;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TCNImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ThingMLPackage.eINSTANCE.getTCN();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getHidden_layers()
  {
    return hidden_layers;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setHidden_layers(String newHidden_layers)
  {
    String oldHidden_layers = hidden_layers;
    hidden_layers = newHidden_layers;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.TCN__HIDDEN_LAYERS, oldHidden_layers, hidden_layers));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<IntegerLiteral> getUnits()
  {
    if (units == null)
    {
      units = new EObjectContainmentEList<IntegerLiteral>(IntegerLiteral.class, this, ThingMLPackage.TCN__UNITS);
    }
    return units;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegerLiteral getNb_filters()
  {
    return nb_filters;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNb_filters(IntegerLiteral newNb_filters, NotificationChain msgs)
  {
    IntegerLiteral oldNb_filters = nb_filters;
    nb_filters = newNb_filters;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.TCN__NB_FILTERS, oldNb_filters, newNb_filters);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNb_filters(IntegerLiteral newNb_filters)
  {
    if (newNb_filters != nb_filters)
    {
      NotificationChain msgs = null;
      if (nb_filters != null)
        msgs = ((InternalEObject)nb_filters).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.TCN__NB_FILTERS, null, msgs);
      if (newNb_filters != null)
        msgs = ((InternalEObject)newNb_filters).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.TCN__NB_FILTERS, null, msgs);
      msgs = basicSetNb_filters(newNb_filters, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.TCN__NB_FILTERS, newNb_filters, newNb_filters));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegerLiteral getKernel_size()
  {
    return kernel_size;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetKernel_size(IntegerLiteral newKernel_size, NotificationChain msgs)
  {
    IntegerLiteral oldKernel_size = kernel_size;
    kernel_size = newKernel_size;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.TCN__KERNEL_SIZE, oldKernel_size, newKernel_size);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setKernel_size(IntegerLiteral newKernel_size)
  {
    if (newKernel_size != kernel_size)
    {
      NotificationChain msgs = null;
      if (kernel_size != null)
        msgs = ((InternalEObject)kernel_size).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.TCN__KERNEL_SIZE, null, msgs);
      if (newKernel_size != null)
        msgs = ((InternalEObject)newKernel_size).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.TCN__KERNEL_SIZE, null, msgs);
      msgs = basicSetKernel_size(newKernel_size, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.TCN__KERNEL_SIZE, newKernel_size, newKernel_size));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDilations()
  {
    return dilations;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDilations(String newDilations)
  {
    String oldDilations = dilations;
    dilations = newDilations;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.TCN__DILATIONS, oldDilations, dilations));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegerLiteral getNb_stacks()
  {
    return nb_stacks;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNb_stacks(IntegerLiteral newNb_stacks, NotificationChain msgs)
  {
    IntegerLiteral oldNb_stacks = nb_stacks;
    nb_stacks = newNb_stacks;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.TCN__NB_STACKS, oldNb_stacks, newNb_stacks);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNb_stacks(IntegerLiteral newNb_stacks)
  {
    if (newNb_stacks != nb_stacks)
    {
      NotificationChain msgs = null;
      if (nb_stacks != null)
        msgs = ((InternalEObject)nb_stacks).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.TCN__NB_STACKS, null, msgs);
      if (newNb_stacks != null)
        msgs = ((InternalEObject)newNb_stacks).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.TCN__NB_STACKS, null, msgs);
      msgs = basicSetNb_stacks(newNb_stacks, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.TCN__NB_STACKS, newNb_stacks, newNb_stacks));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public double getDropout_rate()
  {
    return dropout_rate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDropout_rate(double newDropout_rate)
  {
    double oldDropout_rate = dropout_rate;
    dropout_rate = newDropout_rate;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.TCN__DROPOUT_RATE, oldDropout_rate, dropout_rate));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Activation getActivation()
  {
    return activation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setActivation(Activation newActivation)
  {
    Activation oldActivation = activation;
    activation = newActivation == null ? ACTIVATION_EDEFAULT : newActivation;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.TCN__ACTIVATION, oldActivation, activation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public double getLearning_rate()
  {
    return learning_rate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLearning_rate(double newLearning_rate)
  {
    double oldLearning_rate = learning_rate;
    learning_rate = newLearning_rate;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.TCN__LEARNING_RATE, oldLearning_rate, learning_rate));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Loss getLoss()
  {
    return loss;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLoss(Loss newLoss)
  {
    Loss oldLoss = loss;
    loss = newLoss == null ? LOSS_EDEFAULT : newLoss;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.TCN__LOSS, oldLoss, loss));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDense_layers()
  {
    return dense_layers;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDense_layers(String newDense_layers)
  {
    String oldDense_layers = dense_layers;
    dense_layers = newDense_layers;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.TCN__DENSE_LAYERS, oldDense_layers, dense_layers));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<IntegerLiteral> getNeurons()
  {
    if (neurons == null)
    {
      neurons = new EObjectContainmentEList<IntegerLiteral>(IntegerLiteral.class, this, ThingMLPackage.TCN__NEURONS);
    }
    return neurons;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ThingMLPackage.TCN__UNITS:
        return ((InternalEList<?>)getUnits()).basicRemove(otherEnd, msgs);
      case ThingMLPackage.TCN__NB_FILTERS:
        return basicSetNb_filters(null, msgs);
      case ThingMLPackage.TCN__KERNEL_SIZE:
        return basicSetKernel_size(null, msgs);
      case ThingMLPackage.TCN__NB_STACKS:
        return basicSetNb_stacks(null, msgs);
      case ThingMLPackage.TCN__NEURONS:
        return ((InternalEList<?>)getNeurons()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ThingMLPackage.TCN__HIDDEN_LAYERS:
        return getHidden_layers();
      case ThingMLPackage.TCN__UNITS:
        return getUnits();
      case ThingMLPackage.TCN__NB_FILTERS:
        return getNb_filters();
      case ThingMLPackage.TCN__KERNEL_SIZE:
        return getKernel_size();
      case ThingMLPackage.TCN__DILATIONS:
        return getDilations();
      case ThingMLPackage.TCN__NB_STACKS:
        return getNb_stacks();
      case ThingMLPackage.TCN__DROPOUT_RATE:
        return getDropout_rate();
      case ThingMLPackage.TCN__ACTIVATION:
        return getActivation();
      case ThingMLPackage.TCN__LEARNING_RATE:
        return getLearning_rate();
      case ThingMLPackage.TCN__LOSS:
        return getLoss();
      case ThingMLPackage.TCN__DENSE_LAYERS:
        return getDense_layers();
      case ThingMLPackage.TCN__NEURONS:
        return getNeurons();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ThingMLPackage.TCN__HIDDEN_LAYERS:
        setHidden_layers((String)newValue);
        return;
      case ThingMLPackage.TCN__UNITS:
        getUnits().clear();
        getUnits().addAll((Collection<? extends IntegerLiteral>)newValue);
        return;
      case ThingMLPackage.TCN__NB_FILTERS:
        setNb_filters((IntegerLiteral)newValue);
        return;
      case ThingMLPackage.TCN__KERNEL_SIZE:
        setKernel_size((IntegerLiteral)newValue);
        return;
      case ThingMLPackage.TCN__DILATIONS:
        setDilations((String)newValue);
        return;
      case ThingMLPackage.TCN__NB_STACKS:
        setNb_stacks((IntegerLiteral)newValue);
        return;
      case ThingMLPackage.TCN__DROPOUT_RATE:
        setDropout_rate((Double)newValue);
        return;
      case ThingMLPackage.TCN__ACTIVATION:
        setActivation((Activation)newValue);
        return;
      case ThingMLPackage.TCN__LEARNING_RATE:
        setLearning_rate((Double)newValue);
        return;
      case ThingMLPackage.TCN__LOSS:
        setLoss((Loss)newValue);
        return;
      case ThingMLPackage.TCN__DENSE_LAYERS:
        setDense_layers((String)newValue);
        return;
      case ThingMLPackage.TCN__NEURONS:
        getNeurons().clear();
        getNeurons().addAll((Collection<? extends IntegerLiteral>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ThingMLPackage.TCN__HIDDEN_LAYERS:
        setHidden_layers(HIDDEN_LAYERS_EDEFAULT);
        return;
      case ThingMLPackage.TCN__UNITS:
        getUnits().clear();
        return;
      case ThingMLPackage.TCN__NB_FILTERS:
        setNb_filters((IntegerLiteral)null);
        return;
      case ThingMLPackage.TCN__KERNEL_SIZE:
        setKernel_size((IntegerLiteral)null);
        return;
      case ThingMLPackage.TCN__DILATIONS:
        setDilations(DILATIONS_EDEFAULT);
        return;
      case ThingMLPackage.TCN__NB_STACKS:
        setNb_stacks((IntegerLiteral)null);
        return;
      case ThingMLPackage.TCN__DROPOUT_RATE:
        setDropout_rate(DROPOUT_RATE_EDEFAULT);
        return;
      case ThingMLPackage.TCN__ACTIVATION:
        setActivation(ACTIVATION_EDEFAULT);
        return;
      case ThingMLPackage.TCN__LEARNING_RATE:
        setLearning_rate(LEARNING_RATE_EDEFAULT);
        return;
      case ThingMLPackage.TCN__LOSS:
        setLoss(LOSS_EDEFAULT);
        return;
      case ThingMLPackage.TCN__DENSE_LAYERS:
        setDense_layers(DENSE_LAYERS_EDEFAULT);
        return;
      case ThingMLPackage.TCN__NEURONS:
        getNeurons().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ThingMLPackage.TCN__HIDDEN_LAYERS:
        return HIDDEN_LAYERS_EDEFAULT == null ? hidden_layers != null : !HIDDEN_LAYERS_EDEFAULT.equals(hidden_layers);
      case ThingMLPackage.TCN__UNITS:
        return units != null && !units.isEmpty();
      case ThingMLPackage.TCN__NB_FILTERS:
        return nb_filters != null;
      case ThingMLPackage.TCN__KERNEL_SIZE:
        return kernel_size != null;
      case ThingMLPackage.TCN__DILATIONS:
        return DILATIONS_EDEFAULT == null ? dilations != null : !DILATIONS_EDEFAULT.equals(dilations);
      case ThingMLPackage.TCN__NB_STACKS:
        return nb_stacks != null;
      case ThingMLPackage.TCN__DROPOUT_RATE:
        return dropout_rate != DROPOUT_RATE_EDEFAULT;
      case ThingMLPackage.TCN__ACTIVATION:
        return activation != ACTIVATION_EDEFAULT;
      case ThingMLPackage.TCN__LEARNING_RATE:
        return learning_rate != LEARNING_RATE_EDEFAULT;
      case ThingMLPackage.TCN__LOSS:
        return loss != LOSS_EDEFAULT;
      case ThingMLPackage.TCN__DENSE_LAYERS:
        return DENSE_LAYERS_EDEFAULT == null ? dense_layers != null : !DENSE_LAYERS_EDEFAULT.equals(dense_layers);
      case ThingMLPackage.TCN__NEURONS:
        return neurons != null && !neurons.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (hidden_layers: ");
    result.append(hidden_layers);
    result.append(", dilations: ");
    result.append(dilations);
    result.append(", dropout_rate: ");
    result.append(dropout_rate);
    result.append(", activation: ");
    result.append(activation);
    result.append(", learning_rate: ");
    result.append(learning_rate);
    result.append(", loss: ");
    result.append(loss);
    result.append(", dense_layers: ");
    result.append(dense_layers);
    result.append(')');
    return result.toString();
  }

} //TCNImpl
