/*
 * generated by Xtext 2.38.0
 */
package org.thingml.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.thingml.xtext.ThingML.ui.internal.ThingMLActivator;

public class ThingMLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ThingMLActivator.getInstance().getInjector("org.thingml.xtext.ThingML");
	}

}
