/**
 * generated by Xtext 2.38.0
 */
package org.thingml.xtext.thingML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mini Batch KMeans</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.thingml.xtext.thingML.MiniBatchKMeans#getN_clusters <em>Nclusters</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.MiniBatchKMeans#getInit_enum <em>Init enum</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.MiniBatchKMeans#getInit_str <em>Init str</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.MiniBatchKMeans#getMax_iter <em>Max iter</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.MiniBatchKMeans#getBatch_size <em>Batch size</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.MiniBatchKMeans#getVerbose <em>Verbose</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.MiniBatchKMeans#getCompute_labels <em>Compute labels</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.MiniBatchKMeans#getRandom_state <em>Random state</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.MiniBatchKMeans#getTol <em>Tol</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.MiniBatchKMeans#getMax_no_improvement <em>Max no improvement</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.MiniBatchKMeans#getInit_size <em>Init size</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.MiniBatchKMeans#getN_init <em>Ninit</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.MiniBatchKMeans#getReassignment_ratio <em>Reassignment ratio</em>}</li>
 * </ul>
 *
 * @see org.thingml.xtext.thingML.ThingMLPackage#getMiniBatchKMeans()
 * @model
 * @generated
 */
public interface MiniBatchKMeans extends ML2_ModelAlgorithm
{
  /**
   * Returns the value of the '<em><b>Nclusters</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nclusters</em>' containment reference.
   * @see #setN_clusters(IntegerLiteral)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getMiniBatchKMeans_N_clusters()
   * @model containment="true"
   * @generated
   */
  IntegerLiteral getN_clusters();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.MiniBatchKMeans#getN_clusters <em>Nclusters</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nclusters</em>' containment reference.
   * @see #getN_clusters()
   * @generated
   */
  void setN_clusters(IntegerLiteral value);

  /**
   * Returns the value of the '<em><b>Init enum</b></em>' attribute.
   * The literals are from the enumeration {@link org.thingml.xtext.thingML.KMeans_init_enum}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Init enum</em>' attribute.
   * @see org.thingml.xtext.thingML.KMeans_init_enum
   * @see #setInit_enum(KMeans_init_enum)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getMiniBatchKMeans_Init_enum()
   * @model
   * @generated
   */
  KMeans_init_enum getInit_enum();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.MiniBatchKMeans#getInit_enum <em>Init enum</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Init enum</em>' attribute.
   * @see org.thingml.xtext.thingML.KMeans_init_enum
   * @see #getInit_enum()
   * @generated
   */
  void setInit_enum(KMeans_init_enum value);

  /**
   * Returns the value of the '<em><b>Init str</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Init str</em>' attribute.
   * @see #setInit_str(String)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getMiniBatchKMeans_Init_str()
   * @model
   * @generated
   */
  String getInit_str();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.MiniBatchKMeans#getInit_str <em>Init str</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Init str</em>' attribute.
   * @see #getInit_str()
   * @generated
   */
  void setInit_str(String value);

  /**
   * Returns the value of the '<em><b>Max iter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max iter</em>' containment reference.
   * @see #setMax_iter(IntegerLiteral)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getMiniBatchKMeans_Max_iter()
   * @model containment="true"
   * @generated
   */
  IntegerLiteral getMax_iter();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.MiniBatchKMeans#getMax_iter <em>Max iter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max iter</em>' containment reference.
   * @see #getMax_iter()
   * @generated
   */
  void setMax_iter(IntegerLiteral value);

  /**
   * Returns the value of the '<em><b>Batch size</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Batch size</em>' containment reference.
   * @see #setBatch_size(IntegerLiteral)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getMiniBatchKMeans_Batch_size()
   * @model containment="true"
   * @generated
   */
  IntegerLiteral getBatch_size();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.MiniBatchKMeans#getBatch_size <em>Batch size</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Batch size</em>' containment reference.
   * @see #getBatch_size()
   * @generated
   */
  void setBatch_size(IntegerLiteral value);

  /**
   * Returns the value of the '<em><b>Verbose</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Verbose</em>' containment reference.
   * @see #setVerbose(IntegerLiteral)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getMiniBatchKMeans_Verbose()
   * @model containment="true"
   * @generated
   */
  IntegerLiteral getVerbose();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.MiniBatchKMeans#getVerbose <em>Verbose</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Verbose</em>' containment reference.
   * @see #getVerbose()
   * @generated
   */
  void setVerbose(IntegerLiteral value);

  /**
   * Returns the value of the '<em><b>Compute labels</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Compute labels</em>' containment reference.
   * @see #setCompute_labels(BooleanLiteral)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getMiniBatchKMeans_Compute_labels()
   * @model containment="true"
   * @generated
   */
  BooleanLiteral getCompute_labels();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.MiniBatchKMeans#getCompute_labels <em>Compute labels</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Compute labels</em>' containment reference.
   * @see #getCompute_labels()
   * @generated
   */
  void setCompute_labels(BooleanLiteral value);

  /**
   * Returns the value of the '<em><b>Random state</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Random state</em>' containment reference.
   * @see #setRandom_state(IntegerLiteral)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getMiniBatchKMeans_Random_state()
   * @model containment="true"
   * @generated
   */
  IntegerLiteral getRandom_state();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.MiniBatchKMeans#getRandom_state <em>Random state</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Random state</em>' containment reference.
   * @see #getRandom_state()
   * @generated
   */
  void setRandom_state(IntegerLiteral value);

  /**
   * Returns the value of the '<em><b>Tol</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tol</em>' containment reference.
   * @see #setTol(DoubleLiteral)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getMiniBatchKMeans_Tol()
   * @model containment="true"
   * @generated
   */
  DoubleLiteral getTol();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.MiniBatchKMeans#getTol <em>Tol</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tol</em>' containment reference.
   * @see #getTol()
   * @generated
   */
  void setTol(DoubleLiteral value);

  /**
   * Returns the value of the '<em><b>Max no improvement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max no improvement</em>' containment reference.
   * @see #setMax_no_improvement(IntegerLiteral)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getMiniBatchKMeans_Max_no_improvement()
   * @model containment="true"
   * @generated
   */
  IntegerLiteral getMax_no_improvement();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.MiniBatchKMeans#getMax_no_improvement <em>Max no improvement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max no improvement</em>' containment reference.
   * @see #getMax_no_improvement()
   * @generated
   */
  void setMax_no_improvement(IntegerLiteral value);

  /**
   * Returns the value of the '<em><b>Init size</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Init size</em>' containment reference.
   * @see #setInit_size(IntegerLiteral)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getMiniBatchKMeans_Init_size()
   * @model containment="true"
   * @generated
   */
  IntegerLiteral getInit_size();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.MiniBatchKMeans#getInit_size <em>Init size</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Init size</em>' containment reference.
   * @see #getInit_size()
   * @generated
   */
  void setInit_size(IntegerLiteral value);

  /**
   * Returns the value of the '<em><b>Ninit</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ninit</em>' containment reference.
   * @see #setN_init(IntegerLiteral)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getMiniBatchKMeans_N_init()
   * @model containment="true"
   * @generated
   */
  IntegerLiteral getN_init();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.MiniBatchKMeans#getN_init <em>Ninit</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ninit</em>' containment reference.
   * @see #getN_init()
   * @generated
   */
  void setN_init(IntegerLiteral value);

  /**
   * Returns the value of the '<em><b>Reassignment ratio</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reassignment ratio</em>' containment reference.
   * @see #setReassignment_ratio(DoubleLiteral)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getMiniBatchKMeans_Reassignment_ratio()
   * @model containment="true"
   * @generated
   */
  DoubleLiteral getReassignment_ratio();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.MiniBatchKMeans#getReassignment_ratio <em>Reassignment ratio</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reassignment ratio</em>' containment reference.
   * @see #getReassignment_ratio()
   * @generated
   */
  void setReassignment_ratio(DoubleLiteral value);

} // MiniBatchKMeans
