/**
 * generated by Xtext 2.38.0
 */
package org.thingml.xtext.thingML.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.thingml.xtext.thingML.ClassifierWithPredictionCertaintyProbabilities;
import org.thingml.xtext.thingML.ThingMLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Classifier With Prediction Certainty Probabilities</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ClassifierWithPredictionCertaintyProbabilitiesImpl extends MinimalEObjectImpl.Container implements ClassifierWithPredictionCertaintyProbabilities
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ClassifierWithPredictionCertaintyProbabilitiesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ThingMLPackage.eINSTANCE.getClassifierWithPredictionCertaintyProbabilities();
  }

} //ClassifierWithPredictionCertaintyProbabilitiesImpl
