/**
 * generated by Xtext 2.38.0
 */
package org.thingml.xtext.thingML;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Forecasting Plots</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.thingml.xtext.thingML.ThingMLPackage#getForecastingPlots()
 * @model
 * @generated
 */
public enum ForecastingPlots implements Enumerator
{
  /**
   * The '<em><b>FORECAST VS ACTUAL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FORECAST_VS_ACTUAL_VALUE
   * @generated
   * @ordered
   */
  FORECAST_VS_ACTUAL(0, "FORECAST_VS_ACTUAL", "FORECAST_VS_ACTUAL"),

  /**
   * The '<em><b>FORECAST ERROR</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FORECAST_ERROR_VALUE
   * @generated
   * @ordered
   */
  FORECAST_ERROR(1, "FORECAST_ERROR", "FORECAST_ERROR"),

  /**
   * The '<em><b>FORECAST INTERVALS</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FORECAST_INTERVALS_VALUE
   * @generated
   * @ordered
   */
  FORECAST_INTERVALS(2, "FORECAST_INTERVALS", "FORECAST_INTERVALS");

  /**
   * The '<em><b>FORECAST VS ACTUAL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FORECAST_VS_ACTUAL
   * @model
   * @generated
   * @ordered
   */
  public static final int FORECAST_VS_ACTUAL_VALUE = 0;

  /**
   * The '<em><b>FORECAST ERROR</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FORECAST_ERROR
   * @model
   * @generated
   * @ordered
   */
  public static final int FORECAST_ERROR_VALUE = 1;

  /**
   * The '<em><b>FORECAST INTERVALS</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FORECAST_INTERVALS
   * @model
   * @generated
   * @ordered
   */
  public static final int FORECAST_INTERVALS_VALUE = 2;

  /**
   * An array of all the '<em><b>Forecasting Plots</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final ForecastingPlots[] VALUES_ARRAY =
    new ForecastingPlots[]
    {
      FORECAST_VS_ACTUAL,
      FORECAST_ERROR,
      FORECAST_INTERVALS,
    };

  /**
   * A public read-only list of all the '<em><b>Forecasting Plots</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<ForecastingPlots> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Forecasting Plots</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ForecastingPlots get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ForecastingPlots result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Forecasting Plots</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ForecastingPlots getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ForecastingPlots result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Forecasting Plots</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ForecastingPlots get(int value)
  {
    switch (value)
    {
      case FORECAST_VS_ACTUAL_VALUE: return FORECAST_VS_ACTUAL;
      case FORECAST_ERROR_VALUE: return FORECAST_ERROR;
      case FORECAST_INTERVALS_VALUE: return FORECAST_INTERVALS;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private ForecastingPlots(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //ForecastingPlots
