/**
 * generated by Xtext 2.38.0
 */
package org.thingml.xtext.thingML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>statistical Model Algorithm</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.thingml.xtext.thingML.ThingMLPackage#getstatistical_ModelAlgorithm()
 * @model
 * @generated
 */
public interface statistical_ModelAlgorithm extends Time_series_ModelAlgorithm
{
} // statistical_ModelAlgorithm
