/**
 * generated by Xtext 2.38.0
 */
package org.thingml.xtext.thingML;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transformer</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.thingml.xtext.thingML.Transformer#getHidden_layers <em>Hidden layers</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.Transformer#getUnits <em>Units</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.Transformer#getNum_layers <em>Num layers</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.Transformer#getD_model <em>Dmodel</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.Transformer#getNum_heads <em>Num heads</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.Transformer#getDff <em>Dff</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.Transformer#getDropout_rate <em>Dropout rate</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.Transformer#getActivation <em>Activation</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.Transformer#getLearning_rate <em>Learning rate</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.Transformer#getLoss <em>Loss</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.Transformer#getDense_layers <em>Dense layers</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.Transformer#getNeurons <em>Neurons</em>}</li>
 * </ul>
 *
 * @see org.thingml.xtext.thingML.ThingMLPackage#getTransformer()
 * @model
 * @generated
 */
public interface Transformer extends Deep_learning_ModelAlgorithm
{
  /**
   * Returns the value of the '<em><b>Hidden layers</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hidden layers</em>' attribute.
   * @see #setHidden_layers(String)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getTransformer_Hidden_layers()
   * @model
   * @generated
   */
  String getHidden_layers();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.Transformer#getHidden_layers <em>Hidden layers</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Hidden layers</em>' attribute.
   * @see #getHidden_layers()
   * @generated
   */
  void setHidden_layers(String value);

  /**
   * Returns the value of the '<em><b>Units</b></em>' containment reference list.
   * The list contents are of type {@link org.thingml.xtext.thingML.IntegerLiteral}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Units</em>' containment reference list.
   * @see org.thingml.xtext.thingML.ThingMLPackage#getTransformer_Units()
   * @model containment="true"
   * @generated
   */
  EList<IntegerLiteral> getUnits();

  /**
   * Returns the value of the '<em><b>Num layers</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Num layers</em>' containment reference.
   * @see #setNum_layers(IntegerLiteral)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getTransformer_Num_layers()
   * @model containment="true"
   * @generated
   */
  IntegerLiteral getNum_layers();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.Transformer#getNum_layers <em>Num layers</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Num layers</em>' containment reference.
   * @see #getNum_layers()
   * @generated
   */
  void setNum_layers(IntegerLiteral value);

  /**
   * Returns the value of the '<em><b>Dmodel</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dmodel</em>' containment reference.
   * @see #setD_model(IntegerLiteral)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getTransformer_D_model()
   * @model containment="true"
   * @generated
   */
  IntegerLiteral getD_model();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.Transformer#getD_model <em>Dmodel</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dmodel</em>' containment reference.
   * @see #getD_model()
   * @generated
   */
  void setD_model(IntegerLiteral value);

  /**
   * Returns the value of the '<em><b>Num heads</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Num heads</em>' containment reference.
   * @see #setNum_heads(IntegerLiteral)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getTransformer_Num_heads()
   * @model containment="true"
   * @generated
   */
  IntegerLiteral getNum_heads();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.Transformer#getNum_heads <em>Num heads</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Num heads</em>' containment reference.
   * @see #getNum_heads()
   * @generated
   */
  void setNum_heads(IntegerLiteral value);

  /**
   * Returns the value of the '<em><b>Dff</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dff</em>' containment reference.
   * @see #setDff(IntegerLiteral)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getTransformer_Dff()
   * @model containment="true"
   * @generated
   */
  IntegerLiteral getDff();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.Transformer#getDff <em>Dff</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dff</em>' containment reference.
   * @see #getDff()
   * @generated
   */
  void setDff(IntegerLiteral value);

  /**
   * Returns the value of the '<em><b>Dropout rate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dropout rate</em>' attribute.
   * @see #setDropout_rate(double)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getTransformer_Dropout_rate()
   * @model
   * @generated
   */
  double getDropout_rate();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.Transformer#getDropout_rate <em>Dropout rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dropout rate</em>' attribute.
   * @see #getDropout_rate()
   * @generated
   */
  void setDropout_rate(double value);

  /**
   * Returns the value of the '<em><b>Activation</b></em>' attribute.
   * The literals are from the enumeration {@link org.thingml.xtext.thingML.Activation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Activation</em>' attribute.
   * @see org.thingml.xtext.thingML.Activation
   * @see #setActivation(Activation)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getTransformer_Activation()
   * @model
   * @generated
   */
  Activation getActivation();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.Transformer#getActivation <em>Activation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Activation</em>' attribute.
   * @see org.thingml.xtext.thingML.Activation
   * @see #getActivation()
   * @generated
   */
  void setActivation(Activation value);

  /**
   * Returns the value of the '<em><b>Learning rate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Learning rate</em>' attribute.
   * @see #setLearning_rate(double)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getTransformer_Learning_rate()
   * @model
   * @generated
   */
  double getLearning_rate();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.Transformer#getLearning_rate <em>Learning rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Learning rate</em>' attribute.
   * @see #getLearning_rate()
   * @generated
   */
  void setLearning_rate(double value);

  /**
   * Returns the value of the '<em><b>Loss</b></em>' attribute.
   * The literals are from the enumeration {@link org.thingml.xtext.thingML.Loss}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Loss</em>' attribute.
   * @see org.thingml.xtext.thingML.Loss
   * @see #setLoss(Loss)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getTransformer_Loss()
   * @model
   * @generated
   */
  Loss getLoss();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.Transformer#getLoss <em>Loss</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Loss</em>' attribute.
   * @see org.thingml.xtext.thingML.Loss
   * @see #getLoss()
   * @generated
   */
  void setLoss(Loss value);

  /**
   * Returns the value of the '<em><b>Dense layers</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dense layers</em>' attribute.
   * @see #setDense_layers(String)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getTransformer_Dense_layers()
   * @model
   * @generated
   */
  String getDense_layers();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.Transformer#getDense_layers <em>Dense layers</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dense layers</em>' attribute.
   * @see #getDense_layers()
   * @generated
   */
  void setDense_layers(String value);

  /**
   * Returns the value of the '<em><b>Neurons</b></em>' containment reference list.
   * The list contents are of type {@link org.thingml.xtext.thingML.IntegerLiteral}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Neurons</em>' containment reference list.
   * @see org.thingml.xtext.thingML.ThingMLPackage#getTransformer_Neurons()
   * @model containment="true"
   * @generated
   */
  EList<IntegerLiteral> getNeurons();

} // Transformer
