/*
 * generated by Xtext 2.38.0
 */
package org.thingml.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractThingMLScopeProvider extends DelegatingScopeProvider {
}
