/**
 * generated by Xtext 2.38.0
 */
package org.thingml.xtext.thingML.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.thingml.xtext.thingML.ARIMA;
import org.thingml.xtext.thingML.IntegerLiteral;
import org.thingml.xtext.thingML.ThingMLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>ARIMA</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.thingml.xtext.thingML.impl.ARIMAImpl#getP <em>P</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.ARIMAImpl#getDifferencing <em>Differencing</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.ARIMAImpl#getQ <em>Q</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.ARIMAImpl#getTrend <em>Trend</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.ARIMAImpl#getSeasonalP <em>Seasonal P</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.ARIMAImpl#getSeasonalD <em>Seasonal D</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.ARIMAImpl#getSeasonalQ <em>Seasonal Q</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.ARIMAImpl#getSeasonality <em>Seasonality</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ARIMAImpl extends statistical_ModelAlgorithmImpl implements ARIMA
{
  /**
   * The cached value of the '{@link #getP() <em>P</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getP()
   * @generated
   * @ordered
   */
  protected IntegerLiteral p;

  /**
   * The cached value of the '{@link #getDifferencing() <em>Differencing</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDifferencing()
   * @generated
   * @ordered
   */
  protected IntegerLiteral differencing;

  /**
   * The cached value of the '{@link #getQ() <em>Q</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQ()
   * @generated
   * @ordered
   */
  protected IntegerLiteral q;

  /**
   * The default value of the '{@link #getTrend() <em>Trend</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTrend()
   * @generated
   * @ordered
   */
  protected static final String TREND_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTrend() <em>Trend</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTrend()
   * @generated
   * @ordered
   */
  protected String trend = TREND_EDEFAULT;

  /**
   * The cached value of the '{@link #getSeasonalP() <em>Seasonal P</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSeasonalP()
   * @generated
   * @ordered
   */
  protected IntegerLiteral seasonalP;

  /**
   * The cached value of the '{@link #getSeasonalD() <em>Seasonal D</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSeasonalD()
   * @generated
   * @ordered
   */
  protected IntegerLiteral seasonalD;

  /**
   * The cached value of the '{@link #getSeasonalQ() <em>Seasonal Q</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSeasonalQ()
   * @generated
   * @ordered
   */
  protected IntegerLiteral seasonalQ;

  /**
   * The cached value of the '{@link #getSeasonality() <em>Seasonality</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSeasonality()
   * @generated
   * @ordered
   */
  protected IntegerLiteral seasonality;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ARIMAImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ThingMLPackage.eINSTANCE.getARIMA();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegerLiteral getP()
  {
    return p;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetP(IntegerLiteral newP, NotificationChain msgs)
  {
    IntegerLiteral oldP = p;
    p = newP;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.ARIMA__P, oldP, newP);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setP(IntegerLiteral newP)
  {
    if (newP != p)
    {
      NotificationChain msgs = null;
      if (p != null)
        msgs = ((InternalEObject)p).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.ARIMA__P, null, msgs);
      if (newP != null)
        msgs = ((InternalEObject)newP).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.ARIMA__P, null, msgs);
      msgs = basicSetP(newP, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.ARIMA__P, newP, newP));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegerLiteral getDifferencing()
  {
    return differencing;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDifferencing(IntegerLiteral newDifferencing, NotificationChain msgs)
  {
    IntegerLiteral oldDifferencing = differencing;
    differencing = newDifferencing;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.ARIMA__DIFFERENCING, oldDifferencing, newDifferencing);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDifferencing(IntegerLiteral newDifferencing)
  {
    if (newDifferencing != differencing)
    {
      NotificationChain msgs = null;
      if (differencing != null)
        msgs = ((InternalEObject)differencing).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.ARIMA__DIFFERENCING, null, msgs);
      if (newDifferencing != null)
        msgs = ((InternalEObject)newDifferencing).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.ARIMA__DIFFERENCING, null, msgs);
      msgs = basicSetDifferencing(newDifferencing, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.ARIMA__DIFFERENCING, newDifferencing, newDifferencing));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegerLiteral getQ()
  {
    return q;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetQ(IntegerLiteral newQ, NotificationChain msgs)
  {
    IntegerLiteral oldQ = q;
    q = newQ;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.ARIMA__Q, oldQ, newQ);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setQ(IntegerLiteral newQ)
  {
    if (newQ != q)
    {
      NotificationChain msgs = null;
      if (q != null)
        msgs = ((InternalEObject)q).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.ARIMA__Q, null, msgs);
      if (newQ != null)
        msgs = ((InternalEObject)newQ).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.ARIMA__Q, null, msgs);
      msgs = basicSetQ(newQ, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.ARIMA__Q, newQ, newQ));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTrend()
  {
    return trend;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTrend(String newTrend)
  {
    String oldTrend = trend;
    trend = newTrend;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.ARIMA__TREND, oldTrend, trend));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegerLiteral getSeasonalP()
  {
    return seasonalP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSeasonalP(IntegerLiteral newSeasonalP, NotificationChain msgs)
  {
    IntegerLiteral oldSeasonalP = seasonalP;
    seasonalP = newSeasonalP;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.ARIMA__SEASONAL_P, oldSeasonalP, newSeasonalP);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSeasonalP(IntegerLiteral newSeasonalP)
  {
    if (newSeasonalP != seasonalP)
    {
      NotificationChain msgs = null;
      if (seasonalP != null)
        msgs = ((InternalEObject)seasonalP).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.ARIMA__SEASONAL_P, null, msgs);
      if (newSeasonalP != null)
        msgs = ((InternalEObject)newSeasonalP).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.ARIMA__SEASONAL_P, null, msgs);
      msgs = basicSetSeasonalP(newSeasonalP, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.ARIMA__SEASONAL_P, newSeasonalP, newSeasonalP));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegerLiteral getSeasonalD()
  {
    return seasonalD;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSeasonalD(IntegerLiteral newSeasonalD, NotificationChain msgs)
  {
    IntegerLiteral oldSeasonalD = seasonalD;
    seasonalD = newSeasonalD;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.ARIMA__SEASONAL_D, oldSeasonalD, newSeasonalD);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSeasonalD(IntegerLiteral newSeasonalD)
  {
    if (newSeasonalD != seasonalD)
    {
      NotificationChain msgs = null;
      if (seasonalD != null)
        msgs = ((InternalEObject)seasonalD).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.ARIMA__SEASONAL_D, null, msgs);
      if (newSeasonalD != null)
        msgs = ((InternalEObject)newSeasonalD).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.ARIMA__SEASONAL_D, null, msgs);
      msgs = basicSetSeasonalD(newSeasonalD, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.ARIMA__SEASONAL_D, newSeasonalD, newSeasonalD));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegerLiteral getSeasonalQ()
  {
    return seasonalQ;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSeasonalQ(IntegerLiteral newSeasonalQ, NotificationChain msgs)
  {
    IntegerLiteral oldSeasonalQ = seasonalQ;
    seasonalQ = newSeasonalQ;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.ARIMA__SEASONAL_Q, oldSeasonalQ, newSeasonalQ);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSeasonalQ(IntegerLiteral newSeasonalQ)
  {
    if (newSeasonalQ != seasonalQ)
    {
      NotificationChain msgs = null;
      if (seasonalQ != null)
        msgs = ((InternalEObject)seasonalQ).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.ARIMA__SEASONAL_Q, null, msgs);
      if (newSeasonalQ != null)
        msgs = ((InternalEObject)newSeasonalQ).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.ARIMA__SEASONAL_Q, null, msgs);
      msgs = basicSetSeasonalQ(newSeasonalQ, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.ARIMA__SEASONAL_Q, newSeasonalQ, newSeasonalQ));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegerLiteral getSeasonality()
  {
    return seasonality;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSeasonality(IntegerLiteral newSeasonality, NotificationChain msgs)
  {
    IntegerLiteral oldSeasonality = seasonality;
    seasonality = newSeasonality;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.ARIMA__SEASONALITY, oldSeasonality, newSeasonality);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSeasonality(IntegerLiteral newSeasonality)
  {
    if (newSeasonality != seasonality)
    {
      NotificationChain msgs = null;
      if (seasonality != null)
        msgs = ((InternalEObject)seasonality).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.ARIMA__SEASONALITY, null, msgs);
      if (newSeasonality != null)
        msgs = ((InternalEObject)newSeasonality).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.ARIMA__SEASONALITY, null, msgs);
      msgs = basicSetSeasonality(newSeasonality, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.ARIMA__SEASONALITY, newSeasonality, newSeasonality));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ThingMLPackage.ARIMA__P:
        return basicSetP(null, msgs);
      case ThingMLPackage.ARIMA__DIFFERENCING:
        return basicSetDifferencing(null, msgs);
      case ThingMLPackage.ARIMA__Q:
        return basicSetQ(null, msgs);
      case ThingMLPackage.ARIMA__SEASONAL_P:
        return basicSetSeasonalP(null, msgs);
      case ThingMLPackage.ARIMA__SEASONAL_D:
        return basicSetSeasonalD(null, msgs);
      case ThingMLPackage.ARIMA__SEASONAL_Q:
        return basicSetSeasonalQ(null, msgs);
      case ThingMLPackage.ARIMA__SEASONALITY:
        return basicSetSeasonality(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ThingMLPackage.ARIMA__P:
        return getP();
      case ThingMLPackage.ARIMA__DIFFERENCING:
        return getDifferencing();
      case ThingMLPackage.ARIMA__Q:
        return getQ();
      case ThingMLPackage.ARIMA__TREND:
        return getTrend();
      case ThingMLPackage.ARIMA__SEASONAL_P:
        return getSeasonalP();
      case ThingMLPackage.ARIMA__SEASONAL_D:
        return getSeasonalD();
      case ThingMLPackage.ARIMA__SEASONAL_Q:
        return getSeasonalQ();
      case ThingMLPackage.ARIMA__SEASONALITY:
        return getSeasonality();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ThingMLPackage.ARIMA__P:
        setP((IntegerLiteral)newValue);
        return;
      case ThingMLPackage.ARIMA__DIFFERENCING:
        setDifferencing((IntegerLiteral)newValue);
        return;
      case ThingMLPackage.ARIMA__Q:
        setQ((IntegerLiteral)newValue);
        return;
      case ThingMLPackage.ARIMA__TREND:
        setTrend((String)newValue);
        return;
      case ThingMLPackage.ARIMA__SEASONAL_P:
        setSeasonalP((IntegerLiteral)newValue);
        return;
      case ThingMLPackage.ARIMA__SEASONAL_D:
        setSeasonalD((IntegerLiteral)newValue);
        return;
      case ThingMLPackage.ARIMA__SEASONAL_Q:
        setSeasonalQ((IntegerLiteral)newValue);
        return;
      case ThingMLPackage.ARIMA__SEASONALITY:
        setSeasonality((IntegerLiteral)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ThingMLPackage.ARIMA__P:
        setP((IntegerLiteral)null);
        return;
      case ThingMLPackage.ARIMA__DIFFERENCING:
        setDifferencing((IntegerLiteral)null);
        return;
      case ThingMLPackage.ARIMA__Q:
        setQ((IntegerLiteral)null);
        return;
      case ThingMLPackage.ARIMA__TREND:
        setTrend(TREND_EDEFAULT);
        return;
      case ThingMLPackage.ARIMA__SEASONAL_P:
        setSeasonalP((IntegerLiteral)null);
        return;
      case ThingMLPackage.ARIMA__SEASONAL_D:
        setSeasonalD((IntegerLiteral)null);
        return;
      case ThingMLPackage.ARIMA__SEASONAL_Q:
        setSeasonalQ((IntegerLiteral)null);
        return;
      case ThingMLPackage.ARIMA__SEASONALITY:
        setSeasonality((IntegerLiteral)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ThingMLPackage.ARIMA__P:
        return p != null;
      case ThingMLPackage.ARIMA__DIFFERENCING:
        return differencing != null;
      case ThingMLPackage.ARIMA__Q:
        return q != null;
      case ThingMLPackage.ARIMA__TREND:
        return TREND_EDEFAULT == null ? trend != null : !TREND_EDEFAULT.equals(trend);
      case ThingMLPackage.ARIMA__SEASONAL_P:
        return seasonalP != null;
      case ThingMLPackage.ARIMA__SEASONAL_D:
        return seasonalD != null;
      case ThingMLPackage.ARIMA__SEASONAL_Q:
        return seasonalQ != null;
      case ThingMLPackage.ARIMA__SEASONALITY:
        return seasonality != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (trend: ");
    result.append(trend);
    result.append(')');
    return result.toString();
  }

} //ARIMAImpl
