/**
 * generated by Xtext 2.38.0
 */
package org.thingml.xtext.thingML.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.thingml.xtext.thingML.Activation;
import org.thingml.xtext.thingML.CNN;
import org.thingml.xtext.thingML.IntegerLiteral;
import org.thingml.xtext.thingML.Regularization;
import org.thingml.xtext.thingML.ThingMLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>CNN</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.thingml.xtext.thingML.impl.CNNImpl#getUnits <em>Units</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.CNNImpl#getHidden_layer_sizes <em>Hidden layer sizes</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.CNNImpl#getHidden_layers <em>Hidden layers</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.CNNImpl#getInput_activation <em>Input activation</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.CNNImpl#getHidden_activation <em>Hidden activation</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.CNNImpl#getOutput_activation <em>Output activation</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.CNNImpl#getRegularization <em>Regularization</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.CNNImpl#getDropout <em>Dropout</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.CNNImpl#getRate <em>Rate</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CNNImpl extends Deep_learning_ModelAlgorithmImpl implements CNN
{
  /**
   * The cached value of the '{@link #getUnits() <em>Units</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUnits()
   * @generated
   * @ordered
   */
  protected IntegerLiteral units;

  /**
   * The default value of the '{@link #getHidden_layer_sizes() <em>Hidden layer sizes</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHidden_layer_sizes()
   * @generated
   * @ordered
   */
  protected static final String HIDDEN_LAYER_SIZES_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getHidden_layer_sizes() <em>Hidden layer sizes</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHidden_layer_sizes()
   * @generated
   * @ordered
   */
  protected String hidden_layer_sizes = HIDDEN_LAYER_SIZES_EDEFAULT;

  /**
   * The cached value of the '{@link #getHidden_layers() <em>Hidden layers</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHidden_layers()
   * @generated
   * @ordered
   */
  protected EList<IntegerLiteral> hidden_layers;

  /**
   * The default value of the '{@link #getInput_activation() <em>Input activation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInput_activation()
   * @generated
   * @ordered
   */
  protected static final Activation INPUT_ACTIVATION_EDEFAULT = Activation.NOT_SET;

  /**
   * The cached value of the '{@link #getInput_activation() <em>Input activation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInput_activation()
   * @generated
   * @ordered
   */
  protected Activation input_activation = INPUT_ACTIVATION_EDEFAULT;

  /**
   * The default value of the '{@link #getHidden_activation() <em>Hidden activation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHidden_activation()
   * @generated
   * @ordered
   */
  protected static final Activation HIDDEN_ACTIVATION_EDEFAULT = Activation.NOT_SET;

  /**
   * The cached value of the '{@link #getHidden_activation() <em>Hidden activation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHidden_activation()
   * @generated
   * @ordered
   */
  protected Activation hidden_activation = HIDDEN_ACTIVATION_EDEFAULT;

  /**
   * The default value of the '{@link #getOutput_activation() <em>Output activation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOutput_activation()
   * @generated
   * @ordered
   */
  protected static final Activation OUTPUT_ACTIVATION_EDEFAULT = Activation.NOT_SET;

  /**
   * The cached value of the '{@link #getOutput_activation() <em>Output activation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOutput_activation()
   * @generated
   * @ordered
   */
  protected Activation output_activation = OUTPUT_ACTIVATION_EDEFAULT;

  /**
   * The default value of the '{@link #getRegularization() <em>Regularization</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRegularization()
   * @generated
   * @ordered
   */
  protected static final Regularization REGULARIZATION_EDEFAULT = Regularization.NOT_SET;

  /**
   * The cached value of the '{@link #getRegularization() <em>Regularization</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRegularization()
   * @generated
   * @ordered
   */
  protected Regularization regularization = REGULARIZATION_EDEFAULT;

  /**
   * The default value of the '{@link #getDropout() <em>Dropout</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDropout()
   * @generated
   * @ordered
   */
  protected static final double DROPOUT_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getDropout() <em>Dropout</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDropout()
   * @generated
   * @ordered
   */
  protected double dropout = DROPOUT_EDEFAULT;

  /**
   * The default value of the '{@link #getRate() <em>Rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRate()
   * @generated
   * @ordered
   */
  protected static final double RATE_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getRate() <em>Rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRate()
   * @generated
   * @ordered
   */
  protected double rate = RATE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CNNImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ThingMLPackage.eINSTANCE.getCNN();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegerLiteral getUnits()
  {
    return units;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetUnits(IntegerLiteral newUnits, NotificationChain msgs)
  {
    IntegerLiteral oldUnits = units;
    units = newUnits;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.CNN__UNITS, oldUnits, newUnits);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUnits(IntegerLiteral newUnits)
  {
    if (newUnits != units)
    {
      NotificationChain msgs = null;
      if (units != null)
        msgs = ((InternalEObject)units).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.CNN__UNITS, null, msgs);
      if (newUnits != null)
        msgs = ((InternalEObject)newUnits).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.CNN__UNITS, null, msgs);
      msgs = basicSetUnits(newUnits, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.CNN__UNITS, newUnits, newUnits));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getHidden_layer_sizes()
  {
    return hidden_layer_sizes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setHidden_layer_sizes(String newHidden_layer_sizes)
  {
    String oldHidden_layer_sizes = hidden_layer_sizes;
    hidden_layer_sizes = newHidden_layer_sizes;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.CNN__HIDDEN_LAYER_SIZES, oldHidden_layer_sizes, hidden_layer_sizes));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<IntegerLiteral> getHidden_layers()
  {
    if (hidden_layers == null)
    {
      hidden_layers = new EObjectContainmentEList<IntegerLiteral>(IntegerLiteral.class, this, ThingMLPackage.CNN__HIDDEN_LAYERS);
    }
    return hidden_layers;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Activation getInput_activation()
  {
    return input_activation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInput_activation(Activation newInput_activation)
  {
    Activation oldInput_activation = input_activation;
    input_activation = newInput_activation == null ? INPUT_ACTIVATION_EDEFAULT : newInput_activation;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.CNN__INPUT_ACTIVATION, oldInput_activation, input_activation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Activation getHidden_activation()
  {
    return hidden_activation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setHidden_activation(Activation newHidden_activation)
  {
    Activation oldHidden_activation = hidden_activation;
    hidden_activation = newHidden_activation == null ? HIDDEN_ACTIVATION_EDEFAULT : newHidden_activation;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.CNN__HIDDEN_ACTIVATION, oldHidden_activation, hidden_activation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Activation getOutput_activation()
  {
    return output_activation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOutput_activation(Activation newOutput_activation)
  {
    Activation oldOutput_activation = output_activation;
    output_activation = newOutput_activation == null ? OUTPUT_ACTIVATION_EDEFAULT : newOutput_activation;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.CNN__OUTPUT_ACTIVATION, oldOutput_activation, output_activation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Regularization getRegularization()
  {
    return regularization;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRegularization(Regularization newRegularization)
  {
    Regularization oldRegularization = regularization;
    regularization = newRegularization == null ? REGULARIZATION_EDEFAULT : newRegularization;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.CNN__REGULARIZATION, oldRegularization, regularization));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public double getDropout()
  {
    return dropout;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDropout(double newDropout)
  {
    double oldDropout = dropout;
    dropout = newDropout;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.CNN__DROPOUT, oldDropout, dropout));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public double getRate()
  {
    return rate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRate(double newRate)
  {
    double oldRate = rate;
    rate = newRate;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.CNN__RATE, oldRate, rate));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ThingMLPackage.CNN__UNITS:
        return basicSetUnits(null, msgs);
      case ThingMLPackage.CNN__HIDDEN_LAYERS:
        return ((InternalEList<?>)getHidden_layers()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ThingMLPackage.CNN__UNITS:
        return getUnits();
      case ThingMLPackage.CNN__HIDDEN_LAYER_SIZES:
        return getHidden_layer_sizes();
      case ThingMLPackage.CNN__HIDDEN_LAYERS:
        return getHidden_layers();
      case ThingMLPackage.CNN__INPUT_ACTIVATION:
        return getInput_activation();
      case ThingMLPackage.CNN__HIDDEN_ACTIVATION:
        return getHidden_activation();
      case ThingMLPackage.CNN__OUTPUT_ACTIVATION:
        return getOutput_activation();
      case ThingMLPackage.CNN__REGULARIZATION:
        return getRegularization();
      case ThingMLPackage.CNN__DROPOUT:
        return getDropout();
      case ThingMLPackage.CNN__RATE:
        return getRate();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ThingMLPackage.CNN__UNITS:
        setUnits((IntegerLiteral)newValue);
        return;
      case ThingMLPackage.CNN__HIDDEN_LAYER_SIZES:
        setHidden_layer_sizes((String)newValue);
        return;
      case ThingMLPackage.CNN__HIDDEN_LAYERS:
        getHidden_layers().clear();
        getHidden_layers().addAll((Collection<? extends IntegerLiteral>)newValue);
        return;
      case ThingMLPackage.CNN__INPUT_ACTIVATION:
        setInput_activation((Activation)newValue);
        return;
      case ThingMLPackage.CNN__HIDDEN_ACTIVATION:
        setHidden_activation((Activation)newValue);
        return;
      case ThingMLPackage.CNN__OUTPUT_ACTIVATION:
        setOutput_activation((Activation)newValue);
        return;
      case ThingMLPackage.CNN__REGULARIZATION:
        setRegularization((Regularization)newValue);
        return;
      case ThingMLPackage.CNN__DROPOUT:
        setDropout((Double)newValue);
        return;
      case ThingMLPackage.CNN__RATE:
        setRate((Double)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ThingMLPackage.CNN__UNITS:
        setUnits((IntegerLiteral)null);
        return;
      case ThingMLPackage.CNN__HIDDEN_LAYER_SIZES:
        setHidden_layer_sizes(HIDDEN_LAYER_SIZES_EDEFAULT);
        return;
      case ThingMLPackage.CNN__HIDDEN_LAYERS:
        getHidden_layers().clear();
        return;
      case ThingMLPackage.CNN__INPUT_ACTIVATION:
        setInput_activation(INPUT_ACTIVATION_EDEFAULT);
        return;
      case ThingMLPackage.CNN__HIDDEN_ACTIVATION:
        setHidden_activation(HIDDEN_ACTIVATION_EDEFAULT);
        return;
      case ThingMLPackage.CNN__OUTPUT_ACTIVATION:
        setOutput_activation(OUTPUT_ACTIVATION_EDEFAULT);
        return;
      case ThingMLPackage.CNN__REGULARIZATION:
        setRegularization(REGULARIZATION_EDEFAULT);
        return;
      case ThingMLPackage.CNN__DROPOUT:
        setDropout(DROPOUT_EDEFAULT);
        return;
      case ThingMLPackage.CNN__RATE:
        setRate(RATE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ThingMLPackage.CNN__UNITS:
        return units != null;
      case ThingMLPackage.CNN__HIDDEN_LAYER_SIZES:
        return HIDDEN_LAYER_SIZES_EDEFAULT == null ? hidden_layer_sizes != null : !HIDDEN_LAYER_SIZES_EDEFAULT.equals(hidden_layer_sizes);
      case ThingMLPackage.CNN__HIDDEN_LAYERS:
        return hidden_layers != null && !hidden_layers.isEmpty();
      case ThingMLPackage.CNN__INPUT_ACTIVATION:
        return input_activation != INPUT_ACTIVATION_EDEFAULT;
      case ThingMLPackage.CNN__HIDDEN_ACTIVATION:
        return hidden_activation != HIDDEN_ACTIVATION_EDEFAULT;
      case ThingMLPackage.CNN__OUTPUT_ACTIVATION:
        return output_activation != OUTPUT_ACTIVATION_EDEFAULT;
      case ThingMLPackage.CNN__REGULARIZATION:
        return regularization != REGULARIZATION_EDEFAULT;
      case ThingMLPackage.CNN__DROPOUT:
        return dropout != DROPOUT_EDEFAULT;
      case ThingMLPackage.CNN__RATE:
        return rate != RATE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (hidden_layer_sizes: ");
    result.append(hidden_layer_sizes);
    result.append(", input_activation: ");
    result.append(input_activation);
    result.append(", hidden_activation: ");
    result.append(hidden_activation);
    result.append(", output_activation: ");
    result.append(output_activation);
    result.append(", regularization: ");
    result.append(regularization);
    result.append(", dropout: ");
    result.append(dropout);
    result.append(", rate: ");
    result.append(rate);
    result.append(')');
    return result.toString();
  }

} //CNNImpl
