/**
 * generated by Xtext 2.38.0
 */
package org.thingml.xtext.thingML.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.thingml.xtext.thingML.DBSCAN;
import org.thingml.xtext.thingML.DoubleLiteral;
import org.thingml.xtext.thingML.IntegerLiteral;
import org.thingml.xtext.thingML.KNN_Algorithms;
import org.thingml.xtext.thingML.ThingMLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>DBSCAN</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.thingml.xtext.thingML.impl.DBSCANImpl#getEps <em>Eps</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.DBSCANImpl#getMin_samples <em>Min samples</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.DBSCANImpl#getMetric <em>Metric</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.DBSCANImpl#getMetric_params <em>Metric params</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.DBSCANImpl#getAlgorithm <em>Algorithm</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.DBSCANImpl#getLeaf_size <em>Leaf size</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.DBSCANImpl#getP <em>P</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.DBSCANImpl#getN_jobs <em>Njobs</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DBSCANImpl extends ML2_ModelAlgorithmImpl implements DBSCAN
{
  /**
   * The cached value of the '{@link #getEps() <em>Eps</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEps()
   * @generated
   * @ordered
   */
  protected DoubleLiteral eps;

  /**
   * The cached value of the '{@link #getMin_samples() <em>Min samples</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMin_samples()
   * @generated
   * @ordered
   */
  protected IntegerLiteral min_samples;

  /**
   * The default value of the '{@link #getMetric() <em>Metric</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMetric()
   * @generated
   * @ordered
   */
  protected static final String METRIC_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMetric() <em>Metric</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMetric()
   * @generated
   * @ordered
   */
  protected String metric = METRIC_EDEFAULT;

  /**
   * The default value of the '{@link #getMetric_params() <em>Metric params</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMetric_params()
   * @generated
   * @ordered
   */
  protected static final String METRIC_PARAMS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMetric_params() <em>Metric params</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMetric_params()
   * @generated
   * @ordered
   */
  protected String metric_params = METRIC_PARAMS_EDEFAULT;

  /**
   * The default value of the '{@link #getAlgorithm() <em>Algorithm</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAlgorithm()
   * @generated
   * @ordered
   */
  protected static final KNN_Algorithms ALGORITHM_EDEFAULT = KNN_Algorithms.NOT_SET;

  /**
   * The cached value of the '{@link #getAlgorithm() <em>Algorithm</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAlgorithm()
   * @generated
   * @ordered
   */
  protected KNN_Algorithms algorithm = ALGORITHM_EDEFAULT;

  /**
   * The cached value of the '{@link #getLeaf_size() <em>Leaf size</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLeaf_size()
   * @generated
   * @ordered
   */
  protected IntegerLiteral leaf_size;

  /**
   * The cached value of the '{@link #getP() <em>P</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getP()
   * @generated
   * @ordered
   */
  protected DoubleLiteral p;

  /**
   * The cached value of the '{@link #getN_jobs() <em>Njobs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getN_jobs()
   * @generated
   * @ordered
   */
  protected IntegerLiteral n_jobs;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DBSCANImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ThingMLPackage.eINSTANCE.getDBSCAN();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DoubleLiteral getEps()
  {
    return eps;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEps(DoubleLiteral newEps, NotificationChain msgs)
  {
    DoubleLiteral oldEps = eps;
    eps = newEps;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.DBSCAN__EPS, oldEps, newEps);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEps(DoubleLiteral newEps)
  {
    if (newEps != eps)
    {
      NotificationChain msgs = null;
      if (eps != null)
        msgs = ((InternalEObject)eps).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.DBSCAN__EPS, null, msgs);
      if (newEps != null)
        msgs = ((InternalEObject)newEps).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.DBSCAN__EPS, null, msgs);
      msgs = basicSetEps(newEps, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.DBSCAN__EPS, newEps, newEps));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegerLiteral getMin_samples()
  {
    return min_samples;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetMin_samples(IntegerLiteral newMin_samples, NotificationChain msgs)
  {
    IntegerLiteral oldMin_samples = min_samples;
    min_samples = newMin_samples;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.DBSCAN__MIN_SAMPLES, oldMin_samples, newMin_samples);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMin_samples(IntegerLiteral newMin_samples)
  {
    if (newMin_samples != min_samples)
    {
      NotificationChain msgs = null;
      if (min_samples != null)
        msgs = ((InternalEObject)min_samples).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.DBSCAN__MIN_SAMPLES, null, msgs);
      if (newMin_samples != null)
        msgs = ((InternalEObject)newMin_samples).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.DBSCAN__MIN_SAMPLES, null, msgs);
      msgs = basicSetMin_samples(newMin_samples, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.DBSCAN__MIN_SAMPLES, newMin_samples, newMin_samples));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getMetric()
  {
    return metric;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMetric(String newMetric)
  {
    String oldMetric = metric;
    metric = newMetric;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.DBSCAN__METRIC, oldMetric, metric));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getMetric_params()
  {
    return metric_params;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMetric_params(String newMetric_params)
  {
    String oldMetric_params = metric_params;
    metric_params = newMetric_params;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.DBSCAN__METRIC_PARAMS, oldMetric_params, metric_params));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public KNN_Algorithms getAlgorithm()
  {
    return algorithm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAlgorithm(KNN_Algorithms newAlgorithm)
  {
    KNN_Algorithms oldAlgorithm = algorithm;
    algorithm = newAlgorithm == null ? ALGORITHM_EDEFAULT : newAlgorithm;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.DBSCAN__ALGORITHM, oldAlgorithm, algorithm));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegerLiteral getLeaf_size()
  {
    return leaf_size;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLeaf_size(IntegerLiteral newLeaf_size, NotificationChain msgs)
  {
    IntegerLiteral oldLeaf_size = leaf_size;
    leaf_size = newLeaf_size;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.DBSCAN__LEAF_SIZE, oldLeaf_size, newLeaf_size);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLeaf_size(IntegerLiteral newLeaf_size)
  {
    if (newLeaf_size != leaf_size)
    {
      NotificationChain msgs = null;
      if (leaf_size != null)
        msgs = ((InternalEObject)leaf_size).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.DBSCAN__LEAF_SIZE, null, msgs);
      if (newLeaf_size != null)
        msgs = ((InternalEObject)newLeaf_size).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.DBSCAN__LEAF_SIZE, null, msgs);
      msgs = basicSetLeaf_size(newLeaf_size, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.DBSCAN__LEAF_SIZE, newLeaf_size, newLeaf_size));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DoubleLiteral getP()
  {
    return p;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetP(DoubleLiteral newP, NotificationChain msgs)
  {
    DoubleLiteral oldP = p;
    p = newP;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.DBSCAN__P, oldP, newP);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setP(DoubleLiteral newP)
  {
    if (newP != p)
    {
      NotificationChain msgs = null;
      if (p != null)
        msgs = ((InternalEObject)p).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.DBSCAN__P, null, msgs);
      if (newP != null)
        msgs = ((InternalEObject)newP).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.DBSCAN__P, null, msgs);
      msgs = basicSetP(newP, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.DBSCAN__P, newP, newP));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegerLiteral getN_jobs()
  {
    return n_jobs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetN_jobs(IntegerLiteral newN_jobs, NotificationChain msgs)
  {
    IntegerLiteral oldN_jobs = n_jobs;
    n_jobs = newN_jobs;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.DBSCAN__NJOBS, oldN_jobs, newN_jobs);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setN_jobs(IntegerLiteral newN_jobs)
  {
    if (newN_jobs != n_jobs)
    {
      NotificationChain msgs = null;
      if (n_jobs != null)
        msgs = ((InternalEObject)n_jobs).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.DBSCAN__NJOBS, null, msgs);
      if (newN_jobs != null)
        msgs = ((InternalEObject)newN_jobs).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.DBSCAN__NJOBS, null, msgs);
      msgs = basicSetN_jobs(newN_jobs, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.DBSCAN__NJOBS, newN_jobs, newN_jobs));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ThingMLPackage.DBSCAN__EPS:
        return basicSetEps(null, msgs);
      case ThingMLPackage.DBSCAN__MIN_SAMPLES:
        return basicSetMin_samples(null, msgs);
      case ThingMLPackage.DBSCAN__LEAF_SIZE:
        return basicSetLeaf_size(null, msgs);
      case ThingMLPackage.DBSCAN__P:
        return basicSetP(null, msgs);
      case ThingMLPackage.DBSCAN__NJOBS:
        return basicSetN_jobs(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ThingMLPackage.DBSCAN__EPS:
        return getEps();
      case ThingMLPackage.DBSCAN__MIN_SAMPLES:
        return getMin_samples();
      case ThingMLPackage.DBSCAN__METRIC:
        return getMetric();
      case ThingMLPackage.DBSCAN__METRIC_PARAMS:
        return getMetric_params();
      case ThingMLPackage.DBSCAN__ALGORITHM:
        return getAlgorithm();
      case ThingMLPackage.DBSCAN__LEAF_SIZE:
        return getLeaf_size();
      case ThingMLPackage.DBSCAN__P:
        return getP();
      case ThingMLPackage.DBSCAN__NJOBS:
        return getN_jobs();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ThingMLPackage.DBSCAN__EPS:
        setEps((DoubleLiteral)newValue);
        return;
      case ThingMLPackage.DBSCAN__MIN_SAMPLES:
        setMin_samples((IntegerLiteral)newValue);
        return;
      case ThingMLPackage.DBSCAN__METRIC:
        setMetric((String)newValue);
        return;
      case ThingMLPackage.DBSCAN__METRIC_PARAMS:
        setMetric_params((String)newValue);
        return;
      case ThingMLPackage.DBSCAN__ALGORITHM:
        setAlgorithm((KNN_Algorithms)newValue);
        return;
      case ThingMLPackage.DBSCAN__LEAF_SIZE:
        setLeaf_size((IntegerLiteral)newValue);
        return;
      case ThingMLPackage.DBSCAN__P:
        setP((DoubleLiteral)newValue);
        return;
      case ThingMLPackage.DBSCAN__NJOBS:
        setN_jobs((IntegerLiteral)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ThingMLPackage.DBSCAN__EPS:
        setEps((DoubleLiteral)null);
        return;
      case ThingMLPackage.DBSCAN__MIN_SAMPLES:
        setMin_samples((IntegerLiteral)null);
        return;
      case ThingMLPackage.DBSCAN__METRIC:
        setMetric(METRIC_EDEFAULT);
        return;
      case ThingMLPackage.DBSCAN__METRIC_PARAMS:
        setMetric_params(METRIC_PARAMS_EDEFAULT);
        return;
      case ThingMLPackage.DBSCAN__ALGORITHM:
        setAlgorithm(ALGORITHM_EDEFAULT);
        return;
      case ThingMLPackage.DBSCAN__LEAF_SIZE:
        setLeaf_size((IntegerLiteral)null);
        return;
      case ThingMLPackage.DBSCAN__P:
        setP((DoubleLiteral)null);
        return;
      case ThingMLPackage.DBSCAN__NJOBS:
        setN_jobs((IntegerLiteral)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ThingMLPackage.DBSCAN__EPS:
        return eps != null;
      case ThingMLPackage.DBSCAN__MIN_SAMPLES:
        return min_samples != null;
      case ThingMLPackage.DBSCAN__METRIC:
        return METRIC_EDEFAULT == null ? metric != null : !METRIC_EDEFAULT.equals(metric);
      case ThingMLPackage.DBSCAN__METRIC_PARAMS:
        return METRIC_PARAMS_EDEFAULT == null ? metric_params != null : !METRIC_PARAMS_EDEFAULT.equals(metric_params);
      case ThingMLPackage.DBSCAN__ALGORITHM:
        return algorithm != ALGORITHM_EDEFAULT;
      case ThingMLPackage.DBSCAN__LEAF_SIZE:
        return leaf_size != null;
      case ThingMLPackage.DBSCAN__P:
        return p != null;
      case ThingMLPackage.DBSCAN__NJOBS:
        return n_jobs != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (metric: ");
    result.append(metric);
    result.append(", metric_params: ");
    result.append(metric_params);
    result.append(", algorithm: ");
    result.append(algorithm);
    result.append(')');
    return result.toString();
  }

} //DBSCANImpl
