/**
 * generated by Xtext 2.38.0
 */
package org.thingml.xtext.thingML.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.thingml.xtext.thingML.BooleanLiteral;
import org.thingml.xtext.thingML.ETS;
import org.thingml.xtext.thingML.IntegerLiteral;
import org.thingml.xtext.thingML.ThingMLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>ETS</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.thingml.xtext.thingML.impl.ETSImpl#getError <em>Error</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.ETSImpl#getTrend <em>Trend</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.ETSImpl#getSeasonal <em>Seasonal</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.ETSImpl#getDamped <em>Damped</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.ETSImpl#getSeasonal_periods <em>Seasonal periods</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.ETSImpl#getInitialization_method <em>Initialization method</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.ETSImpl#getUse_boxcox <em>Use boxcox</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.ETSImpl#getRemove_bias <em>Remove bias</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.ETSImpl#getOptimized <em>Optimized</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ETSImpl extends statistical_ModelAlgorithmImpl implements ETS
{
  /**
   * The default value of the '{@link #getError() <em>Error</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getError()
   * @generated
   * @ordered
   */
  protected static final String ERROR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getError() <em>Error</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getError()
   * @generated
   * @ordered
   */
  protected String error = ERROR_EDEFAULT;

  /**
   * The default value of the '{@link #getTrend() <em>Trend</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTrend()
   * @generated
   * @ordered
   */
  protected static final String TREND_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTrend() <em>Trend</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTrend()
   * @generated
   * @ordered
   */
  protected String trend = TREND_EDEFAULT;

  /**
   * The default value of the '{@link #getSeasonal() <em>Seasonal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSeasonal()
   * @generated
   * @ordered
   */
  protected static final String SEASONAL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSeasonal() <em>Seasonal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSeasonal()
   * @generated
   * @ordered
   */
  protected String seasonal = SEASONAL_EDEFAULT;

  /**
   * The cached value of the '{@link #getDamped() <em>Damped</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDamped()
   * @generated
   * @ordered
   */
  protected BooleanLiteral damped;

  /**
   * The cached value of the '{@link #getSeasonal_periods() <em>Seasonal periods</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSeasonal_periods()
   * @generated
   * @ordered
   */
  protected IntegerLiteral seasonal_periods;

  /**
   * The default value of the '{@link #getInitialization_method() <em>Initialization method</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInitialization_method()
   * @generated
   * @ordered
   */
  protected static final String INITIALIZATION_METHOD_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getInitialization_method() <em>Initialization method</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInitialization_method()
   * @generated
   * @ordered
   */
  protected String initialization_method = INITIALIZATION_METHOD_EDEFAULT;

  /**
   * The cached value of the '{@link #getUse_boxcox() <em>Use boxcox</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUse_boxcox()
   * @generated
   * @ordered
   */
  protected BooleanLiteral use_boxcox;

  /**
   * The cached value of the '{@link #getRemove_bias() <em>Remove bias</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRemove_bias()
   * @generated
   * @ordered
   */
  protected BooleanLiteral remove_bias;

  /**
   * The cached value of the '{@link #getOptimized() <em>Optimized</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOptimized()
   * @generated
   * @ordered
   */
  protected BooleanLiteral optimized;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ETSImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ThingMLPackage.eINSTANCE.getETS();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getError()
  {
    return error;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setError(String newError)
  {
    String oldError = error;
    error = newError;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.ETS__ERROR, oldError, error));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTrend()
  {
    return trend;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTrend(String newTrend)
  {
    String oldTrend = trend;
    trend = newTrend;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.ETS__TREND, oldTrend, trend));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSeasonal()
  {
    return seasonal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSeasonal(String newSeasonal)
  {
    String oldSeasonal = seasonal;
    seasonal = newSeasonal;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.ETS__SEASONAL, oldSeasonal, seasonal));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BooleanLiteral getDamped()
  {
    return damped;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDamped(BooleanLiteral newDamped, NotificationChain msgs)
  {
    BooleanLiteral oldDamped = damped;
    damped = newDamped;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.ETS__DAMPED, oldDamped, newDamped);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDamped(BooleanLiteral newDamped)
  {
    if (newDamped != damped)
    {
      NotificationChain msgs = null;
      if (damped != null)
        msgs = ((InternalEObject)damped).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.ETS__DAMPED, null, msgs);
      if (newDamped != null)
        msgs = ((InternalEObject)newDamped).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.ETS__DAMPED, null, msgs);
      msgs = basicSetDamped(newDamped, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.ETS__DAMPED, newDamped, newDamped));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegerLiteral getSeasonal_periods()
  {
    return seasonal_periods;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSeasonal_periods(IntegerLiteral newSeasonal_periods, NotificationChain msgs)
  {
    IntegerLiteral oldSeasonal_periods = seasonal_periods;
    seasonal_periods = newSeasonal_periods;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.ETS__SEASONAL_PERIODS, oldSeasonal_periods, newSeasonal_periods);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSeasonal_periods(IntegerLiteral newSeasonal_periods)
  {
    if (newSeasonal_periods != seasonal_periods)
    {
      NotificationChain msgs = null;
      if (seasonal_periods != null)
        msgs = ((InternalEObject)seasonal_periods).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.ETS__SEASONAL_PERIODS, null, msgs);
      if (newSeasonal_periods != null)
        msgs = ((InternalEObject)newSeasonal_periods).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.ETS__SEASONAL_PERIODS, null, msgs);
      msgs = basicSetSeasonal_periods(newSeasonal_periods, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.ETS__SEASONAL_PERIODS, newSeasonal_periods, newSeasonal_periods));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getInitialization_method()
  {
    return initialization_method;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInitialization_method(String newInitialization_method)
  {
    String oldInitialization_method = initialization_method;
    initialization_method = newInitialization_method;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.ETS__INITIALIZATION_METHOD, oldInitialization_method, initialization_method));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BooleanLiteral getUse_boxcox()
  {
    return use_boxcox;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetUse_boxcox(BooleanLiteral newUse_boxcox, NotificationChain msgs)
  {
    BooleanLiteral oldUse_boxcox = use_boxcox;
    use_boxcox = newUse_boxcox;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.ETS__USE_BOXCOX, oldUse_boxcox, newUse_boxcox);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUse_boxcox(BooleanLiteral newUse_boxcox)
  {
    if (newUse_boxcox != use_boxcox)
    {
      NotificationChain msgs = null;
      if (use_boxcox != null)
        msgs = ((InternalEObject)use_boxcox).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.ETS__USE_BOXCOX, null, msgs);
      if (newUse_boxcox != null)
        msgs = ((InternalEObject)newUse_boxcox).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.ETS__USE_BOXCOX, null, msgs);
      msgs = basicSetUse_boxcox(newUse_boxcox, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.ETS__USE_BOXCOX, newUse_boxcox, newUse_boxcox));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BooleanLiteral getRemove_bias()
  {
    return remove_bias;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRemove_bias(BooleanLiteral newRemove_bias, NotificationChain msgs)
  {
    BooleanLiteral oldRemove_bias = remove_bias;
    remove_bias = newRemove_bias;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.ETS__REMOVE_BIAS, oldRemove_bias, newRemove_bias);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRemove_bias(BooleanLiteral newRemove_bias)
  {
    if (newRemove_bias != remove_bias)
    {
      NotificationChain msgs = null;
      if (remove_bias != null)
        msgs = ((InternalEObject)remove_bias).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.ETS__REMOVE_BIAS, null, msgs);
      if (newRemove_bias != null)
        msgs = ((InternalEObject)newRemove_bias).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.ETS__REMOVE_BIAS, null, msgs);
      msgs = basicSetRemove_bias(newRemove_bias, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.ETS__REMOVE_BIAS, newRemove_bias, newRemove_bias));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BooleanLiteral getOptimized()
  {
    return optimized;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOptimized(BooleanLiteral newOptimized, NotificationChain msgs)
  {
    BooleanLiteral oldOptimized = optimized;
    optimized = newOptimized;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.ETS__OPTIMIZED, oldOptimized, newOptimized);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOptimized(BooleanLiteral newOptimized)
  {
    if (newOptimized != optimized)
    {
      NotificationChain msgs = null;
      if (optimized != null)
        msgs = ((InternalEObject)optimized).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.ETS__OPTIMIZED, null, msgs);
      if (newOptimized != null)
        msgs = ((InternalEObject)newOptimized).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.ETS__OPTIMIZED, null, msgs);
      msgs = basicSetOptimized(newOptimized, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.ETS__OPTIMIZED, newOptimized, newOptimized));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ThingMLPackage.ETS__DAMPED:
        return basicSetDamped(null, msgs);
      case ThingMLPackage.ETS__SEASONAL_PERIODS:
        return basicSetSeasonal_periods(null, msgs);
      case ThingMLPackage.ETS__USE_BOXCOX:
        return basicSetUse_boxcox(null, msgs);
      case ThingMLPackage.ETS__REMOVE_BIAS:
        return basicSetRemove_bias(null, msgs);
      case ThingMLPackage.ETS__OPTIMIZED:
        return basicSetOptimized(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ThingMLPackage.ETS__ERROR:
        return getError();
      case ThingMLPackage.ETS__TREND:
        return getTrend();
      case ThingMLPackage.ETS__SEASONAL:
        return getSeasonal();
      case ThingMLPackage.ETS__DAMPED:
        return getDamped();
      case ThingMLPackage.ETS__SEASONAL_PERIODS:
        return getSeasonal_periods();
      case ThingMLPackage.ETS__INITIALIZATION_METHOD:
        return getInitialization_method();
      case ThingMLPackage.ETS__USE_BOXCOX:
        return getUse_boxcox();
      case ThingMLPackage.ETS__REMOVE_BIAS:
        return getRemove_bias();
      case ThingMLPackage.ETS__OPTIMIZED:
        return getOptimized();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ThingMLPackage.ETS__ERROR:
        setError((String)newValue);
        return;
      case ThingMLPackage.ETS__TREND:
        setTrend((String)newValue);
        return;
      case ThingMLPackage.ETS__SEASONAL:
        setSeasonal((String)newValue);
        return;
      case ThingMLPackage.ETS__DAMPED:
        setDamped((BooleanLiteral)newValue);
        return;
      case ThingMLPackage.ETS__SEASONAL_PERIODS:
        setSeasonal_periods((IntegerLiteral)newValue);
        return;
      case ThingMLPackage.ETS__INITIALIZATION_METHOD:
        setInitialization_method((String)newValue);
        return;
      case ThingMLPackage.ETS__USE_BOXCOX:
        setUse_boxcox((BooleanLiteral)newValue);
        return;
      case ThingMLPackage.ETS__REMOVE_BIAS:
        setRemove_bias((BooleanLiteral)newValue);
        return;
      case ThingMLPackage.ETS__OPTIMIZED:
        setOptimized((BooleanLiteral)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ThingMLPackage.ETS__ERROR:
        setError(ERROR_EDEFAULT);
        return;
      case ThingMLPackage.ETS__TREND:
        setTrend(TREND_EDEFAULT);
        return;
      case ThingMLPackage.ETS__SEASONAL:
        setSeasonal(SEASONAL_EDEFAULT);
        return;
      case ThingMLPackage.ETS__DAMPED:
        setDamped((BooleanLiteral)null);
        return;
      case ThingMLPackage.ETS__SEASONAL_PERIODS:
        setSeasonal_periods((IntegerLiteral)null);
        return;
      case ThingMLPackage.ETS__INITIALIZATION_METHOD:
        setInitialization_method(INITIALIZATION_METHOD_EDEFAULT);
        return;
      case ThingMLPackage.ETS__USE_BOXCOX:
        setUse_boxcox((BooleanLiteral)null);
        return;
      case ThingMLPackage.ETS__REMOVE_BIAS:
        setRemove_bias((BooleanLiteral)null);
        return;
      case ThingMLPackage.ETS__OPTIMIZED:
        setOptimized((BooleanLiteral)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ThingMLPackage.ETS__ERROR:
        return ERROR_EDEFAULT == null ? error != null : !ERROR_EDEFAULT.equals(error);
      case ThingMLPackage.ETS__TREND:
        return TREND_EDEFAULT == null ? trend != null : !TREND_EDEFAULT.equals(trend);
      case ThingMLPackage.ETS__SEASONAL:
        return SEASONAL_EDEFAULT == null ? seasonal != null : !SEASONAL_EDEFAULT.equals(seasonal);
      case ThingMLPackage.ETS__DAMPED:
        return damped != null;
      case ThingMLPackage.ETS__SEASONAL_PERIODS:
        return seasonal_periods != null;
      case ThingMLPackage.ETS__INITIALIZATION_METHOD:
        return INITIALIZATION_METHOD_EDEFAULT == null ? initialization_method != null : !INITIALIZATION_METHOD_EDEFAULT.equals(initialization_method);
      case ThingMLPackage.ETS__USE_BOXCOX:
        return use_boxcox != null;
      case ThingMLPackage.ETS__REMOVE_BIAS:
        return remove_bias != null;
      case ThingMLPackage.ETS__OPTIMIZED:
        return optimized != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (error: ");
    result.append(error);
    result.append(", trend: ");
    result.append(trend);
    result.append(", seasonal: ");
    result.append(seasonal);
    result.append(", initialization_method: ");
    result.append(initialization_method);
    result.append(')');
    return result.toString();
  }

} //ETSImpl
