/**
 * generated by Xtext 2.38.0
 */
package org.thingml.xtext.thingML.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.thingml.xtext.thingML.BooleanLiteral;
import org.thingml.xtext.thingML.GBM;
import org.thingml.xtext.thingML.IntegerLiteral;
import org.thingml.xtext.thingML.ThingMLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>GBM</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.thingml.xtext.thingML.impl.GBMImpl#getLoss <em>Loss</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.GBMImpl#getLearning_rate <em>Learning rate</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.GBMImpl#getN_estimators <em>Nestimators</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.GBMImpl#getSubsample <em>Subsample</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.GBMImpl#getCriterion <em>Criterion</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.GBMImpl#getMin_samples_split <em>Min samples split</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.GBMImpl#getMin_samples_leaf <em>Min samples leaf</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.GBMImpl#getMin_weight_fraction_leaf <em>Min weight fraction leaf</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.GBMImpl#getMax_depth <em>Max depth</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.GBMImpl#getMin_impurity_decrease <em>Min impurity decrease</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.GBMImpl#getInit <em>Init</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.GBMImpl#getRandom_state <em>Random state</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.GBMImpl#getMax_features <em>Max features</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.GBMImpl#getAlpha <em>Alpha</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.GBMImpl#getVerbose <em>Verbose</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.GBMImpl#getMax_leaf_nodes <em>Max leaf nodes</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.GBMImpl#getWarm_start <em>Warm start</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.GBMImpl#getPresort <em>Presort</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GBMImpl extends machine_learning_ModelAlgorithmImpl implements GBM
{
  /**
   * The default value of the '{@link #getLoss() <em>Loss</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLoss()
   * @generated
   * @ordered
   */
  protected static final String LOSS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLoss() <em>Loss</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLoss()
   * @generated
   * @ordered
   */
  protected String loss = LOSS_EDEFAULT;

  /**
   * The default value of the '{@link #getLearning_rate() <em>Learning rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLearning_rate()
   * @generated
   * @ordered
   */
  protected static final double LEARNING_RATE_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getLearning_rate() <em>Learning rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLearning_rate()
   * @generated
   * @ordered
   */
  protected double learning_rate = LEARNING_RATE_EDEFAULT;

  /**
   * The cached value of the '{@link #getN_estimators() <em>Nestimators</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getN_estimators()
   * @generated
   * @ordered
   */
  protected IntegerLiteral n_estimators;

  /**
   * The default value of the '{@link #getSubsample() <em>Subsample</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubsample()
   * @generated
   * @ordered
   */
  protected static final double SUBSAMPLE_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getSubsample() <em>Subsample</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubsample()
   * @generated
   * @ordered
   */
  protected double subsample = SUBSAMPLE_EDEFAULT;

  /**
   * The default value of the '{@link #getCriterion() <em>Criterion</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCriterion()
   * @generated
   * @ordered
   */
  protected static final String CRITERION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCriterion() <em>Criterion</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCriterion()
   * @generated
   * @ordered
   */
  protected String criterion = CRITERION_EDEFAULT;

  /**
   * The cached value of the '{@link #getMin_samples_split() <em>Min samples split</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMin_samples_split()
   * @generated
   * @ordered
   */
  protected IntegerLiteral min_samples_split;

  /**
   * The cached value of the '{@link #getMin_samples_leaf() <em>Min samples leaf</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMin_samples_leaf()
   * @generated
   * @ordered
   */
  protected IntegerLiteral min_samples_leaf;

  /**
   * The default value of the '{@link #getMin_weight_fraction_leaf() <em>Min weight fraction leaf</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMin_weight_fraction_leaf()
   * @generated
   * @ordered
   */
  protected static final double MIN_WEIGHT_FRACTION_LEAF_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getMin_weight_fraction_leaf() <em>Min weight fraction leaf</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMin_weight_fraction_leaf()
   * @generated
   * @ordered
   */
  protected double min_weight_fraction_leaf = MIN_WEIGHT_FRACTION_LEAF_EDEFAULT;

  /**
   * The cached value of the '{@link #getMax_depth() <em>Max depth</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMax_depth()
   * @generated
   * @ordered
   */
  protected IntegerLiteral max_depth;

  /**
   * The default value of the '{@link #getMin_impurity_decrease() <em>Min impurity decrease</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMin_impurity_decrease()
   * @generated
   * @ordered
   */
  protected static final double MIN_IMPURITY_DECREASE_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getMin_impurity_decrease() <em>Min impurity decrease</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMin_impurity_decrease()
   * @generated
   * @ordered
   */
  protected double min_impurity_decrease = MIN_IMPURITY_DECREASE_EDEFAULT;

  /**
   * The default value of the '{@link #getInit() <em>Init</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInit()
   * @generated
   * @ordered
   */
  protected static final String INIT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getInit() <em>Init</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInit()
   * @generated
   * @ordered
   */
  protected String init = INIT_EDEFAULT;

  /**
   * The cached value of the '{@link #getRandom_state() <em>Random state</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRandom_state()
   * @generated
   * @ordered
   */
  protected IntegerLiteral random_state;

  /**
   * The default value of the '{@link #getMax_features() <em>Max features</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMax_features()
   * @generated
   * @ordered
   */
  protected static final String MAX_FEATURES_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMax_features() <em>Max features</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMax_features()
   * @generated
   * @ordered
   */
  protected String max_features = MAX_FEATURES_EDEFAULT;

  /**
   * The default value of the '{@link #getAlpha() <em>Alpha</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAlpha()
   * @generated
   * @ordered
   */
  protected static final double ALPHA_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getAlpha() <em>Alpha</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAlpha()
   * @generated
   * @ordered
   */
  protected double alpha = ALPHA_EDEFAULT;

  /**
   * The cached value of the '{@link #getVerbose() <em>Verbose</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVerbose()
   * @generated
   * @ordered
   */
  protected BooleanLiteral verbose;

  /**
   * The cached value of the '{@link #getMax_leaf_nodes() <em>Max leaf nodes</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMax_leaf_nodes()
   * @generated
   * @ordered
   */
  protected IntegerLiteral max_leaf_nodes;

  /**
   * The cached value of the '{@link #getWarm_start() <em>Warm start</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWarm_start()
   * @generated
   * @ordered
   */
  protected BooleanLiteral warm_start;

  /**
   * The cached value of the '{@link #getPresort() <em>Presort</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPresort()
   * @generated
   * @ordered
   */
  protected BooleanLiteral presort;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GBMImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ThingMLPackage.eINSTANCE.getGBM();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLoss()
  {
    return loss;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLoss(String newLoss)
  {
    String oldLoss = loss;
    loss = newLoss;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.GBM__LOSS, oldLoss, loss));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public double getLearning_rate()
  {
    return learning_rate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLearning_rate(double newLearning_rate)
  {
    double oldLearning_rate = learning_rate;
    learning_rate = newLearning_rate;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.GBM__LEARNING_RATE, oldLearning_rate, learning_rate));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegerLiteral getN_estimators()
  {
    return n_estimators;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetN_estimators(IntegerLiteral newN_estimators, NotificationChain msgs)
  {
    IntegerLiteral oldN_estimators = n_estimators;
    n_estimators = newN_estimators;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.GBM__NESTIMATORS, oldN_estimators, newN_estimators);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setN_estimators(IntegerLiteral newN_estimators)
  {
    if (newN_estimators != n_estimators)
    {
      NotificationChain msgs = null;
      if (n_estimators != null)
        msgs = ((InternalEObject)n_estimators).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.GBM__NESTIMATORS, null, msgs);
      if (newN_estimators != null)
        msgs = ((InternalEObject)newN_estimators).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.GBM__NESTIMATORS, null, msgs);
      msgs = basicSetN_estimators(newN_estimators, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.GBM__NESTIMATORS, newN_estimators, newN_estimators));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public double getSubsample()
  {
    return subsample;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSubsample(double newSubsample)
  {
    double oldSubsample = subsample;
    subsample = newSubsample;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.GBM__SUBSAMPLE, oldSubsample, subsample));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCriterion()
  {
    return criterion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCriterion(String newCriterion)
  {
    String oldCriterion = criterion;
    criterion = newCriterion;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.GBM__CRITERION, oldCriterion, criterion));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegerLiteral getMin_samples_split()
  {
    return min_samples_split;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetMin_samples_split(IntegerLiteral newMin_samples_split, NotificationChain msgs)
  {
    IntegerLiteral oldMin_samples_split = min_samples_split;
    min_samples_split = newMin_samples_split;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.GBM__MIN_SAMPLES_SPLIT, oldMin_samples_split, newMin_samples_split);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMin_samples_split(IntegerLiteral newMin_samples_split)
  {
    if (newMin_samples_split != min_samples_split)
    {
      NotificationChain msgs = null;
      if (min_samples_split != null)
        msgs = ((InternalEObject)min_samples_split).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.GBM__MIN_SAMPLES_SPLIT, null, msgs);
      if (newMin_samples_split != null)
        msgs = ((InternalEObject)newMin_samples_split).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.GBM__MIN_SAMPLES_SPLIT, null, msgs);
      msgs = basicSetMin_samples_split(newMin_samples_split, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.GBM__MIN_SAMPLES_SPLIT, newMin_samples_split, newMin_samples_split));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegerLiteral getMin_samples_leaf()
  {
    return min_samples_leaf;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetMin_samples_leaf(IntegerLiteral newMin_samples_leaf, NotificationChain msgs)
  {
    IntegerLiteral oldMin_samples_leaf = min_samples_leaf;
    min_samples_leaf = newMin_samples_leaf;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.GBM__MIN_SAMPLES_LEAF, oldMin_samples_leaf, newMin_samples_leaf);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMin_samples_leaf(IntegerLiteral newMin_samples_leaf)
  {
    if (newMin_samples_leaf != min_samples_leaf)
    {
      NotificationChain msgs = null;
      if (min_samples_leaf != null)
        msgs = ((InternalEObject)min_samples_leaf).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.GBM__MIN_SAMPLES_LEAF, null, msgs);
      if (newMin_samples_leaf != null)
        msgs = ((InternalEObject)newMin_samples_leaf).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.GBM__MIN_SAMPLES_LEAF, null, msgs);
      msgs = basicSetMin_samples_leaf(newMin_samples_leaf, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.GBM__MIN_SAMPLES_LEAF, newMin_samples_leaf, newMin_samples_leaf));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public double getMin_weight_fraction_leaf()
  {
    return min_weight_fraction_leaf;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMin_weight_fraction_leaf(double newMin_weight_fraction_leaf)
  {
    double oldMin_weight_fraction_leaf = min_weight_fraction_leaf;
    min_weight_fraction_leaf = newMin_weight_fraction_leaf;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.GBM__MIN_WEIGHT_FRACTION_LEAF, oldMin_weight_fraction_leaf, min_weight_fraction_leaf));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegerLiteral getMax_depth()
  {
    return max_depth;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetMax_depth(IntegerLiteral newMax_depth, NotificationChain msgs)
  {
    IntegerLiteral oldMax_depth = max_depth;
    max_depth = newMax_depth;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.GBM__MAX_DEPTH, oldMax_depth, newMax_depth);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMax_depth(IntegerLiteral newMax_depth)
  {
    if (newMax_depth != max_depth)
    {
      NotificationChain msgs = null;
      if (max_depth != null)
        msgs = ((InternalEObject)max_depth).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.GBM__MAX_DEPTH, null, msgs);
      if (newMax_depth != null)
        msgs = ((InternalEObject)newMax_depth).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.GBM__MAX_DEPTH, null, msgs);
      msgs = basicSetMax_depth(newMax_depth, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.GBM__MAX_DEPTH, newMax_depth, newMax_depth));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public double getMin_impurity_decrease()
  {
    return min_impurity_decrease;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMin_impurity_decrease(double newMin_impurity_decrease)
  {
    double oldMin_impurity_decrease = min_impurity_decrease;
    min_impurity_decrease = newMin_impurity_decrease;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.GBM__MIN_IMPURITY_DECREASE, oldMin_impurity_decrease, min_impurity_decrease));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getInit()
  {
    return init;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInit(String newInit)
  {
    String oldInit = init;
    init = newInit;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.GBM__INIT, oldInit, init));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegerLiteral getRandom_state()
  {
    return random_state;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRandom_state(IntegerLiteral newRandom_state, NotificationChain msgs)
  {
    IntegerLiteral oldRandom_state = random_state;
    random_state = newRandom_state;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.GBM__RANDOM_STATE, oldRandom_state, newRandom_state);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRandom_state(IntegerLiteral newRandom_state)
  {
    if (newRandom_state != random_state)
    {
      NotificationChain msgs = null;
      if (random_state != null)
        msgs = ((InternalEObject)random_state).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.GBM__RANDOM_STATE, null, msgs);
      if (newRandom_state != null)
        msgs = ((InternalEObject)newRandom_state).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.GBM__RANDOM_STATE, null, msgs);
      msgs = basicSetRandom_state(newRandom_state, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.GBM__RANDOM_STATE, newRandom_state, newRandom_state));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getMax_features()
  {
    return max_features;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMax_features(String newMax_features)
  {
    String oldMax_features = max_features;
    max_features = newMax_features;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.GBM__MAX_FEATURES, oldMax_features, max_features));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public double getAlpha()
  {
    return alpha;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAlpha(double newAlpha)
  {
    double oldAlpha = alpha;
    alpha = newAlpha;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.GBM__ALPHA, oldAlpha, alpha));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BooleanLiteral getVerbose()
  {
    return verbose;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetVerbose(BooleanLiteral newVerbose, NotificationChain msgs)
  {
    BooleanLiteral oldVerbose = verbose;
    verbose = newVerbose;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.GBM__VERBOSE, oldVerbose, newVerbose);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVerbose(BooleanLiteral newVerbose)
  {
    if (newVerbose != verbose)
    {
      NotificationChain msgs = null;
      if (verbose != null)
        msgs = ((InternalEObject)verbose).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.GBM__VERBOSE, null, msgs);
      if (newVerbose != null)
        msgs = ((InternalEObject)newVerbose).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.GBM__VERBOSE, null, msgs);
      msgs = basicSetVerbose(newVerbose, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.GBM__VERBOSE, newVerbose, newVerbose));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegerLiteral getMax_leaf_nodes()
  {
    return max_leaf_nodes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetMax_leaf_nodes(IntegerLiteral newMax_leaf_nodes, NotificationChain msgs)
  {
    IntegerLiteral oldMax_leaf_nodes = max_leaf_nodes;
    max_leaf_nodes = newMax_leaf_nodes;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.GBM__MAX_LEAF_NODES, oldMax_leaf_nodes, newMax_leaf_nodes);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMax_leaf_nodes(IntegerLiteral newMax_leaf_nodes)
  {
    if (newMax_leaf_nodes != max_leaf_nodes)
    {
      NotificationChain msgs = null;
      if (max_leaf_nodes != null)
        msgs = ((InternalEObject)max_leaf_nodes).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.GBM__MAX_LEAF_NODES, null, msgs);
      if (newMax_leaf_nodes != null)
        msgs = ((InternalEObject)newMax_leaf_nodes).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.GBM__MAX_LEAF_NODES, null, msgs);
      msgs = basicSetMax_leaf_nodes(newMax_leaf_nodes, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.GBM__MAX_LEAF_NODES, newMax_leaf_nodes, newMax_leaf_nodes));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BooleanLiteral getWarm_start()
  {
    return warm_start;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetWarm_start(BooleanLiteral newWarm_start, NotificationChain msgs)
  {
    BooleanLiteral oldWarm_start = warm_start;
    warm_start = newWarm_start;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.GBM__WARM_START, oldWarm_start, newWarm_start);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setWarm_start(BooleanLiteral newWarm_start)
  {
    if (newWarm_start != warm_start)
    {
      NotificationChain msgs = null;
      if (warm_start != null)
        msgs = ((InternalEObject)warm_start).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.GBM__WARM_START, null, msgs);
      if (newWarm_start != null)
        msgs = ((InternalEObject)newWarm_start).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.GBM__WARM_START, null, msgs);
      msgs = basicSetWarm_start(newWarm_start, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.GBM__WARM_START, newWarm_start, newWarm_start));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BooleanLiteral getPresort()
  {
    return presort;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPresort(BooleanLiteral newPresort, NotificationChain msgs)
  {
    BooleanLiteral oldPresort = presort;
    presort = newPresort;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.GBM__PRESORT, oldPresort, newPresort);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPresort(BooleanLiteral newPresort)
  {
    if (newPresort != presort)
    {
      NotificationChain msgs = null;
      if (presort != null)
        msgs = ((InternalEObject)presort).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.GBM__PRESORT, null, msgs);
      if (newPresort != null)
        msgs = ((InternalEObject)newPresort).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.GBM__PRESORT, null, msgs);
      msgs = basicSetPresort(newPresort, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.GBM__PRESORT, newPresort, newPresort));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ThingMLPackage.GBM__NESTIMATORS:
        return basicSetN_estimators(null, msgs);
      case ThingMLPackage.GBM__MIN_SAMPLES_SPLIT:
        return basicSetMin_samples_split(null, msgs);
      case ThingMLPackage.GBM__MIN_SAMPLES_LEAF:
        return basicSetMin_samples_leaf(null, msgs);
      case ThingMLPackage.GBM__MAX_DEPTH:
        return basicSetMax_depth(null, msgs);
      case ThingMLPackage.GBM__RANDOM_STATE:
        return basicSetRandom_state(null, msgs);
      case ThingMLPackage.GBM__VERBOSE:
        return basicSetVerbose(null, msgs);
      case ThingMLPackage.GBM__MAX_LEAF_NODES:
        return basicSetMax_leaf_nodes(null, msgs);
      case ThingMLPackage.GBM__WARM_START:
        return basicSetWarm_start(null, msgs);
      case ThingMLPackage.GBM__PRESORT:
        return basicSetPresort(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ThingMLPackage.GBM__LOSS:
        return getLoss();
      case ThingMLPackage.GBM__LEARNING_RATE:
        return getLearning_rate();
      case ThingMLPackage.GBM__NESTIMATORS:
        return getN_estimators();
      case ThingMLPackage.GBM__SUBSAMPLE:
        return getSubsample();
      case ThingMLPackage.GBM__CRITERION:
        return getCriterion();
      case ThingMLPackage.GBM__MIN_SAMPLES_SPLIT:
        return getMin_samples_split();
      case ThingMLPackage.GBM__MIN_SAMPLES_LEAF:
        return getMin_samples_leaf();
      case ThingMLPackage.GBM__MIN_WEIGHT_FRACTION_LEAF:
        return getMin_weight_fraction_leaf();
      case ThingMLPackage.GBM__MAX_DEPTH:
        return getMax_depth();
      case ThingMLPackage.GBM__MIN_IMPURITY_DECREASE:
        return getMin_impurity_decrease();
      case ThingMLPackage.GBM__INIT:
        return getInit();
      case ThingMLPackage.GBM__RANDOM_STATE:
        return getRandom_state();
      case ThingMLPackage.GBM__MAX_FEATURES:
        return getMax_features();
      case ThingMLPackage.GBM__ALPHA:
        return getAlpha();
      case ThingMLPackage.GBM__VERBOSE:
        return getVerbose();
      case ThingMLPackage.GBM__MAX_LEAF_NODES:
        return getMax_leaf_nodes();
      case ThingMLPackage.GBM__WARM_START:
        return getWarm_start();
      case ThingMLPackage.GBM__PRESORT:
        return getPresort();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ThingMLPackage.GBM__LOSS:
        setLoss((String)newValue);
        return;
      case ThingMLPackage.GBM__LEARNING_RATE:
        setLearning_rate((Double)newValue);
        return;
      case ThingMLPackage.GBM__NESTIMATORS:
        setN_estimators((IntegerLiteral)newValue);
        return;
      case ThingMLPackage.GBM__SUBSAMPLE:
        setSubsample((Double)newValue);
        return;
      case ThingMLPackage.GBM__CRITERION:
        setCriterion((String)newValue);
        return;
      case ThingMLPackage.GBM__MIN_SAMPLES_SPLIT:
        setMin_samples_split((IntegerLiteral)newValue);
        return;
      case ThingMLPackage.GBM__MIN_SAMPLES_LEAF:
        setMin_samples_leaf((IntegerLiteral)newValue);
        return;
      case ThingMLPackage.GBM__MIN_WEIGHT_FRACTION_LEAF:
        setMin_weight_fraction_leaf((Double)newValue);
        return;
      case ThingMLPackage.GBM__MAX_DEPTH:
        setMax_depth((IntegerLiteral)newValue);
        return;
      case ThingMLPackage.GBM__MIN_IMPURITY_DECREASE:
        setMin_impurity_decrease((Double)newValue);
        return;
      case ThingMLPackage.GBM__INIT:
        setInit((String)newValue);
        return;
      case ThingMLPackage.GBM__RANDOM_STATE:
        setRandom_state((IntegerLiteral)newValue);
        return;
      case ThingMLPackage.GBM__MAX_FEATURES:
        setMax_features((String)newValue);
        return;
      case ThingMLPackage.GBM__ALPHA:
        setAlpha((Double)newValue);
        return;
      case ThingMLPackage.GBM__VERBOSE:
        setVerbose((BooleanLiteral)newValue);
        return;
      case ThingMLPackage.GBM__MAX_LEAF_NODES:
        setMax_leaf_nodes((IntegerLiteral)newValue);
        return;
      case ThingMLPackage.GBM__WARM_START:
        setWarm_start((BooleanLiteral)newValue);
        return;
      case ThingMLPackage.GBM__PRESORT:
        setPresort((BooleanLiteral)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ThingMLPackage.GBM__LOSS:
        setLoss(LOSS_EDEFAULT);
        return;
      case ThingMLPackage.GBM__LEARNING_RATE:
        setLearning_rate(LEARNING_RATE_EDEFAULT);
        return;
      case ThingMLPackage.GBM__NESTIMATORS:
        setN_estimators((IntegerLiteral)null);
        return;
      case ThingMLPackage.GBM__SUBSAMPLE:
        setSubsample(SUBSAMPLE_EDEFAULT);
        return;
      case ThingMLPackage.GBM__CRITERION:
        setCriterion(CRITERION_EDEFAULT);
        return;
      case ThingMLPackage.GBM__MIN_SAMPLES_SPLIT:
        setMin_samples_split((IntegerLiteral)null);
        return;
      case ThingMLPackage.GBM__MIN_SAMPLES_LEAF:
        setMin_samples_leaf((IntegerLiteral)null);
        return;
      case ThingMLPackage.GBM__MIN_WEIGHT_FRACTION_LEAF:
        setMin_weight_fraction_leaf(MIN_WEIGHT_FRACTION_LEAF_EDEFAULT);
        return;
      case ThingMLPackage.GBM__MAX_DEPTH:
        setMax_depth((IntegerLiteral)null);
        return;
      case ThingMLPackage.GBM__MIN_IMPURITY_DECREASE:
        setMin_impurity_decrease(MIN_IMPURITY_DECREASE_EDEFAULT);
        return;
      case ThingMLPackage.GBM__INIT:
        setInit(INIT_EDEFAULT);
        return;
      case ThingMLPackage.GBM__RANDOM_STATE:
        setRandom_state((IntegerLiteral)null);
        return;
      case ThingMLPackage.GBM__MAX_FEATURES:
        setMax_features(MAX_FEATURES_EDEFAULT);
        return;
      case ThingMLPackage.GBM__ALPHA:
        setAlpha(ALPHA_EDEFAULT);
        return;
      case ThingMLPackage.GBM__VERBOSE:
        setVerbose((BooleanLiteral)null);
        return;
      case ThingMLPackage.GBM__MAX_LEAF_NODES:
        setMax_leaf_nodes((IntegerLiteral)null);
        return;
      case ThingMLPackage.GBM__WARM_START:
        setWarm_start((BooleanLiteral)null);
        return;
      case ThingMLPackage.GBM__PRESORT:
        setPresort((BooleanLiteral)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ThingMLPackage.GBM__LOSS:
        return LOSS_EDEFAULT == null ? loss != null : !LOSS_EDEFAULT.equals(loss);
      case ThingMLPackage.GBM__LEARNING_RATE:
        return learning_rate != LEARNING_RATE_EDEFAULT;
      case ThingMLPackage.GBM__NESTIMATORS:
        return n_estimators != null;
      case ThingMLPackage.GBM__SUBSAMPLE:
        return subsample != SUBSAMPLE_EDEFAULT;
      case ThingMLPackage.GBM__CRITERION:
        return CRITERION_EDEFAULT == null ? criterion != null : !CRITERION_EDEFAULT.equals(criterion);
      case ThingMLPackage.GBM__MIN_SAMPLES_SPLIT:
        return min_samples_split != null;
      case ThingMLPackage.GBM__MIN_SAMPLES_LEAF:
        return min_samples_leaf != null;
      case ThingMLPackage.GBM__MIN_WEIGHT_FRACTION_LEAF:
        return min_weight_fraction_leaf != MIN_WEIGHT_FRACTION_LEAF_EDEFAULT;
      case ThingMLPackage.GBM__MAX_DEPTH:
        return max_depth != null;
      case ThingMLPackage.GBM__MIN_IMPURITY_DECREASE:
        return min_impurity_decrease != MIN_IMPURITY_DECREASE_EDEFAULT;
      case ThingMLPackage.GBM__INIT:
        return INIT_EDEFAULT == null ? init != null : !INIT_EDEFAULT.equals(init);
      case ThingMLPackage.GBM__RANDOM_STATE:
        return random_state != null;
      case ThingMLPackage.GBM__MAX_FEATURES:
        return MAX_FEATURES_EDEFAULT == null ? max_features != null : !MAX_FEATURES_EDEFAULT.equals(max_features);
      case ThingMLPackage.GBM__ALPHA:
        return alpha != ALPHA_EDEFAULT;
      case ThingMLPackage.GBM__VERBOSE:
        return verbose != null;
      case ThingMLPackage.GBM__MAX_LEAF_NODES:
        return max_leaf_nodes != null;
      case ThingMLPackage.GBM__WARM_START:
        return warm_start != null;
      case ThingMLPackage.GBM__PRESORT:
        return presort != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (loss: ");
    result.append(loss);
    result.append(", learning_rate: ");
    result.append(learning_rate);
    result.append(", subsample: ");
    result.append(subsample);
    result.append(", criterion: ");
    result.append(criterion);
    result.append(", min_weight_fraction_leaf: ");
    result.append(min_weight_fraction_leaf);
    result.append(", min_impurity_decrease: ");
    result.append(min_impurity_decrease);
    result.append(", init: ");
    result.append(init);
    result.append(", max_features: ");
    result.append(max_features);
    result.append(", alpha: ");
    result.append(alpha);
    result.append(')');
    return result.toString();
  }

} //GBMImpl
