/**
 * generated by Xtext 2.38.0
 */
package org.thingml.xtext.thingML.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.thingml.xtext.thingML.BooleanLiteral;
import org.thingml.xtext.thingML.DoubleLiteral;
import org.thingml.xtext.thingML.IntegerLiteral;
import org.thingml.xtext.thingML.KMeans;
import org.thingml.xtext.thingML.KMeans_algorithm_enum;
import org.thingml.xtext.thingML.KMeans_init_enum;
import org.thingml.xtext.thingML.ThingMLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>KMeans</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.thingml.xtext.thingML.impl.KMeansImpl#getN_clusters <em>Nclusters</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.KMeansImpl#getInit_enum <em>Init enum</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.KMeansImpl#getInit_str <em>Init str</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.KMeansImpl#getN_init <em>Ninit</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.KMeansImpl#getMax_iter <em>Max iter</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.KMeansImpl#getTol <em>Tol</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.KMeansImpl#getVerbose <em>Verbose</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.KMeansImpl#getRandom_state <em>Random state</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.KMeansImpl#getCopy_x <em>Copy x</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.KMeansImpl#getN_jobs <em>Njobs</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.impl.KMeansImpl#getAlgorithm <em>Algorithm</em>}</li>
 * </ul>
 *
 * @generated
 */
public class KMeansImpl extends ML2_ModelAlgorithmImpl implements KMeans
{
  /**
   * The cached value of the '{@link #getN_clusters() <em>Nclusters</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getN_clusters()
   * @generated
   * @ordered
   */
  protected IntegerLiteral n_clusters;

  /**
   * The default value of the '{@link #getInit_enum() <em>Init enum</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInit_enum()
   * @generated
   * @ordered
   */
  protected static final KMeans_init_enum INIT_ENUM_EDEFAULT = KMeans_init_enum.NOT_SET;

  /**
   * The cached value of the '{@link #getInit_enum() <em>Init enum</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInit_enum()
   * @generated
   * @ordered
   */
  protected KMeans_init_enum init_enum = INIT_ENUM_EDEFAULT;

  /**
   * The default value of the '{@link #getInit_str() <em>Init str</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInit_str()
   * @generated
   * @ordered
   */
  protected static final String INIT_STR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getInit_str() <em>Init str</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInit_str()
   * @generated
   * @ordered
   */
  protected String init_str = INIT_STR_EDEFAULT;

  /**
   * The cached value of the '{@link #getN_init() <em>Ninit</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getN_init()
   * @generated
   * @ordered
   */
  protected IntegerLiteral n_init;

  /**
   * The cached value of the '{@link #getMax_iter() <em>Max iter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMax_iter()
   * @generated
   * @ordered
   */
  protected IntegerLiteral max_iter;

  /**
   * The cached value of the '{@link #getTol() <em>Tol</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTol()
   * @generated
   * @ordered
   */
  protected DoubleLiteral tol;

  /**
   * The cached value of the '{@link #getVerbose() <em>Verbose</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVerbose()
   * @generated
   * @ordered
   */
  protected IntegerLiteral verbose;

  /**
   * The cached value of the '{@link #getRandom_state() <em>Random state</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRandom_state()
   * @generated
   * @ordered
   */
  protected IntegerLiteral random_state;

  /**
   * The cached value of the '{@link #getCopy_x() <em>Copy x</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCopy_x()
   * @generated
   * @ordered
   */
  protected BooleanLiteral copy_x;

  /**
   * The cached value of the '{@link #getN_jobs() <em>Njobs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getN_jobs()
   * @generated
   * @ordered
   */
  protected IntegerLiteral n_jobs;

  /**
   * The default value of the '{@link #getAlgorithm() <em>Algorithm</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAlgorithm()
   * @generated
   * @ordered
   */
  protected static final KMeans_algorithm_enum ALGORITHM_EDEFAULT = KMeans_algorithm_enum.NOT_SET;

  /**
   * The cached value of the '{@link #getAlgorithm() <em>Algorithm</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAlgorithm()
   * @generated
   * @ordered
   */
  protected KMeans_algorithm_enum algorithm = ALGORITHM_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected KMeansImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ThingMLPackage.eINSTANCE.getKMeans();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegerLiteral getN_clusters()
  {
    return n_clusters;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetN_clusters(IntegerLiteral newN_clusters, NotificationChain msgs)
  {
    IntegerLiteral oldN_clusters = n_clusters;
    n_clusters = newN_clusters;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.KMEANS__NCLUSTERS, oldN_clusters, newN_clusters);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setN_clusters(IntegerLiteral newN_clusters)
  {
    if (newN_clusters != n_clusters)
    {
      NotificationChain msgs = null;
      if (n_clusters != null)
        msgs = ((InternalEObject)n_clusters).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.KMEANS__NCLUSTERS, null, msgs);
      if (newN_clusters != null)
        msgs = ((InternalEObject)newN_clusters).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.KMEANS__NCLUSTERS, null, msgs);
      msgs = basicSetN_clusters(newN_clusters, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.KMEANS__NCLUSTERS, newN_clusters, newN_clusters));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public KMeans_init_enum getInit_enum()
  {
    return init_enum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInit_enum(KMeans_init_enum newInit_enum)
  {
    KMeans_init_enum oldInit_enum = init_enum;
    init_enum = newInit_enum == null ? INIT_ENUM_EDEFAULT : newInit_enum;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.KMEANS__INIT_ENUM, oldInit_enum, init_enum));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getInit_str()
  {
    return init_str;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInit_str(String newInit_str)
  {
    String oldInit_str = init_str;
    init_str = newInit_str;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.KMEANS__INIT_STR, oldInit_str, init_str));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegerLiteral getN_init()
  {
    return n_init;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetN_init(IntegerLiteral newN_init, NotificationChain msgs)
  {
    IntegerLiteral oldN_init = n_init;
    n_init = newN_init;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.KMEANS__NINIT, oldN_init, newN_init);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setN_init(IntegerLiteral newN_init)
  {
    if (newN_init != n_init)
    {
      NotificationChain msgs = null;
      if (n_init != null)
        msgs = ((InternalEObject)n_init).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.KMEANS__NINIT, null, msgs);
      if (newN_init != null)
        msgs = ((InternalEObject)newN_init).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.KMEANS__NINIT, null, msgs);
      msgs = basicSetN_init(newN_init, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.KMEANS__NINIT, newN_init, newN_init));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegerLiteral getMax_iter()
  {
    return max_iter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetMax_iter(IntegerLiteral newMax_iter, NotificationChain msgs)
  {
    IntegerLiteral oldMax_iter = max_iter;
    max_iter = newMax_iter;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.KMEANS__MAX_ITER, oldMax_iter, newMax_iter);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMax_iter(IntegerLiteral newMax_iter)
  {
    if (newMax_iter != max_iter)
    {
      NotificationChain msgs = null;
      if (max_iter != null)
        msgs = ((InternalEObject)max_iter).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.KMEANS__MAX_ITER, null, msgs);
      if (newMax_iter != null)
        msgs = ((InternalEObject)newMax_iter).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.KMEANS__MAX_ITER, null, msgs);
      msgs = basicSetMax_iter(newMax_iter, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.KMEANS__MAX_ITER, newMax_iter, newMax_iter));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DoubleLiteral getTol()
  {
    return tol;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTol(DoubleLiteral newTol, NotificationChain msgs)
  {
    DoubleLiteral oldTol = tol;
    tol = newTol;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.KMEANS__TOL, oldTol, newTol);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTol(DoubleLiteral newTol)
  {
    if (newTol != tol)
    {
      NotificationChain msgs = null;
      if (tol != null)
        msgs = ((InternalEObject)tol).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.KMEANS__TOL, null, msgs);
      if (newTol != null)
        msgs = ((InternalEObject)newTol).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.KMEANS__TOL, null, msgs);
      msgs = basicSetTol(newTol, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.KMEANS__TOL, newTol, newTol));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegerLiteral getVerbose()
  {
    return verbose;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetVerbose(IntegerLiteral newVerbose, NotificationChain msgs)
  {
    IntegerLiteral oldVerbose = verbose;
    verbose = newVerbose;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.KMEANS__VERBOSE, oldVerbose, newVerbose);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVerbose(IntegerLiteral newVerbose)
  {
    if (newVerbose != verbose)
    {
      NotificationChain msgs = null;
      if (verbose != null)
        msgs = ((InternalEObject)verbose).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.KMEANS__VERBOSE, null, msgs);
      if (newVerbose != null)
        msgs = ((InternalEObject)newVerbose).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.KMEANS__VERBOSE, null, msgs);
      msgs = basicSetVerbose(newVerbose, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.KMEANS__VERBOSE, newVerbose, newVerbose));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegerLiteral getRandom_state()
  {
    return random_state;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRandom_state(IntegerLiteral newRandom_state, NotificationChain msgs)
  {
    IntegerLiteral oldRandom_state = random_state;
    random_state = newRandom_state;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.KMEANS__RANDOM_STATE, oldRandom_state, newRandom_state);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRandom_state(IntegerLiteral newRandom_state)
  {
    if (newRandom_state != random_state)
    {
      NotificationChain msgs = null;
      if (random_state != null)
        msgs = ((InternalEObject)random_state).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.KMEANS__RANDOM_STATE, null, msgs);
      if (newRandom_state != null)
        msgs = ((InternalEObject)newRandom_state).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.KMEANS__RANDOM_STATE, null, msgs);
      msgs = basicSetRandom_state(newRandom_state, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.KMEANS__RANDOM_STATE, newRandom_state, newRandom_state));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BooleanLiteral getCopy_x()
  {
    return copy_x;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCopy_x(BooleanLiteral newCopy_x, NotificationChain msgs)
  {
    BooleanLiteral oldCopy_x = copy_x;
    copy_x = newCopy_x;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.KMEANS__COPY_X, oldCopy_x, newCopy_x);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCopy_x(BooleanLiteral newCopy_x)
  {
    if (newCopy_x != copy_x)
    {
      NotificationChain msgs = null;
      if (copy_x != null)
        msgs = ((InternalEObject)copy_x).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.KMEANS__COPY_X, null, msgs);
      if (newCopy_x != null)
        msgs = ((InternalEObject)newCopy_x).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.KMEANS__COPY_X, null, msgs);
      msgs = basicSetCopy_x(newCopy_x, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.KMEANS__COPY_X, newCopy_x, newCopy_x));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegerLiteral getN_jobs()
  {
    return n_jobs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetN_jobs(IntegerLiteral newN_jobs, NotificationChain msgs)
  {
    IntegerLiteral oldN_jobs = n_jobs;
    n_jobs = newN_jobs;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ThingMLPackage.KMEANS__NJOBS, oldN_jobs, newN_jobs);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setN_jobs(IntegerLiteral newN_jobs)
  {
    if (newN_jobs != n_jobs)
    {
      NotificationChain msgs = null;
      if (n_jobs != null)
        msgs = ((InternalEObject)n_jobs).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.KMEANS__NJOBS, null, msgs);
      if (newN_jobs != null)
        msgs = ((InternalEObject)newN_jobs).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ThingMLPackage.KMEANS__NJOBS, null, msgs);
      msgs = basicSetN_jobs(newN_jobs, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.KMEANS__NJOBS, newN_jobs, newN_jobs));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public KMeans_algorithm_enum getAlgorithm()
  {
    return algorithm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAlgorithm(KMeans_algorithm_enum newAlgorithm)
  {
    KMeans_algorithm_enum oldAlgorithm = algorithm;
    algorithm = newAlgorithm == null ? ALGORITHM_EDEFAULT : newAlgorithm;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ThingMLPackage.KMEANS__ALGORITHM, oldAlgorithm, algorithm));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ThingMLPackage.KMEANS__NCLUSTERS:
        return basicSetN_clusters(null, msgs);
      case ThingMLPackage.KMEANS__NINIT:
        return basicSetN_init(null, msgs);
      case ThingMLPackage.KMEANS__MAX_ITER:
        return basicSetMax_iter(null, msgs);
      case ThingMLPackage.KMEANS__TOL:
        return basicSetTol(null, msgs);
      case ThingMLPackage.KMEANS__VERBOSE:
        return basicSetVerbose(null, msgs);
      case ThingMLPackage.KMEANS__RANDOM_STATE:
        return basicSetRandom_state(null, msgs);
      case ThingMLPackage.KMEANS__COPY_X:
        return basicSetCopy_x(null, msgs);
      case ThingMLPackage.KMEANS__NJOBS:
        return basicSetN_jobs(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ThingMLPackage.KMEANS__NCLUSTERS:
        return getN_clusters();
      case ThingMLPackage.KMEANS__INIT_ENUM:
        return getInit_enum();
      case ThingMLPackage.KMEANS__INIT_STR:
        return getInit_str();
      case ThingMLPackage.KMEANS__NINIT:
        return getN_init();
      case ThingMLPackage.KMEANS__MAX_ITER:
        return getMax_iter();
      case ThingMLPackage.KMEANS__TOL:
        return getTol();
      case ThingMLPackage.KMEANS__VERBOSE:
        return getVerbose();
      case ThingMLPackage.KMEANS__RANDOM_STATE:
        return getRandom_state();
      case ThingMLPackage.KMEANS__COPY_X:
        return getCopy_x();
      case ThingMLPackage.KMEANS__NJOBS:
        return getN_jobs();
      case ThingMLPackage.KMEANS__ALGORITHM:
        return getAlgorithm();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ThingMLPackage.KMEANS__NCLUSTERS:
        setN_clusters((IntegerLiteral)newValue);
        return;
      case ThingMLPackage.KMEANS__INIT_ENUM:
        setInit_enum((KMeans_init_enum)newValue);
        return;
      case ThingMLPackage.KMEANS__INIT_STR:
        setInit_str((String)newValue);
        return;
      case ThingMLPackage.KMEANS__NINIT:
        setN_init((IntegerLiteral)newValue);
        return;
      case ThingMLPackage.KMEANS__MAX_ITER:
        setMax_iter((IntegerLiteral)newValue);
        return;
      case ThingMLPackage.KMEANS__TOL:
        setTol((DoubleLiteral)newValue);
        return;
      case ThingMLPackage.KMEANS__VERBOSE:
        setVerbose((IntegerLiteral)newValue);
        return;
      case ThingMLPackage.KMEANS__RANDOM_STATE:
        setRandom_state((IntegerLiteral)newValue);
        return;
      case ThingMLPackage.KMEANS__COPY_X:
        setCopy_x((BooleanLiteral)newValue);
        return;
      case ThingMLPackage.KMEANS__NJOBS:
        setN_jobs((IntegerLiteral)newValue);
        return;
      case ThingMLPackage.KMEANS__ALGORITHM:
        setAlgorithm((KMeans_algorithm_enum)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ThingMLPackage.KMEANS__NCLUSTERS:
        setN_clusters((IntegerLiteral)null);
        return;
      case ThingMLPackage.KMEANS__INIT_ENUM:
        setInit_enum(INIT_ENUM_EDEFAULT);
        return;
      case ThingMLPackage.KMEANS__INIT_STR:
        setInit_str(INIT_STR_EDEFAULT);
        return;
      case ThingMLPackage.KMEANS__NINIT:
        setN_init((IntegerLiteral)null);
        return;
      case ThingMLPackage.KMEANS__MAX_ITER:
        setMax_iter((IntegerLiteral)null);
        return;
      case ThingMLPackage.KMEANS__TOL:
        setTol((DoubleLiteral)null);
        return;
      case ThingMLPackage.KMEANS__VERBOSE:
        setVerbose((IntegerLiteral)null);
        return;
      case ThingMLPackage.KMEANS__RANDOM_STATE:
        setRandom_state((IntegerLiteral)null);
        return;
      case ThingMLPackage.KMEANS__COPY_X:
        setCopy_x((BooleanLiteral)null);
        return;
      case ThingMLPackage.KMEANS__NJOBS:
        setN_jobs((IntegerLiteral)null);
        return;
      case ThingMLPackage.KMEANS__ALGORITHM:
        setAlgorithm(ALGORITHM_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ThingMLPackage.KMEANS__NCLUSTERS:
        return n_clusters != null;
      case ThingMLPackage.KMEANS__INIT_ENUM:
        return init_enum != INIT_ENUM_EDEFAULT;
      case ThingMLPackage.KMEANS__INIT_STR:
        return INIT_STR_EDEFAULT == null ? init_str != null : !INIT_STR_EDEFAULT.equals(init_str);
      case ThingMLPackage.KMEANS__NINIT:
        return n_init != null;
      case ThingMLPackage.KMEANS__MAX_ITER:
        return max_iter != null;
      case ThingMLPackage.KMEANS__TOL:
        return tol != null;
      case ThingMLPackage.KMEANS__VERBOSE:
        return verbose != null;
      case ThingMLPackage.KMEANS__RANDOM_STATE:
        return random_state != null;
      case ThingMLPackage.KMEANS__COPY_X:
        return copy_x != null;
      case ThingMLPackage.KMEANS__NJOBS:
        return n_jobs != null;
      case ThingMLPackage.KMEANS__ALGORITHM:
        return algorithm != ALGORITHM_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (init_enum: ");
    result.append(init_enum);
    result.append(", init_str: ");
    result.append(init_str);
    result.append(", algorithm: ");
    result.append(algorithm);
    result.append(')');
    return result.toString();
  }

} //KMeansImpl
