/**
 * generated by Xtext 2.38.0
 */
package org.thingml.xtext.thingML.tests;

import junit.textui.TestRunner;

import org.thingml.xtext.thingML.Deep_learning_ModelAlgorithm;
import org.thingml.xtext.thingML.ThingMLFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Deep learning Model Algorithm</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class Deep_learning_ModelAlgorithmTest extends Time_series_ModelAlgorithmTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(Deep_learning_ModelAlgorithmTest.class);
	}

	/**
	 * Constructs a new Deep learning Model Algorithm test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Deep_learning_ModelAlgorithmTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Deep learning Model Algorithm test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected Deep_learning_ModelAlgorithm getFixture() {
		return (Deep_learning_ModelAlgorithm)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(ThingMLFactory.eINSTANCE.createDeep_learning_ModelAlgorithm());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //Deep_learning_ModelAlgorithmTest
