/**
 * generated by Xtext 2.38.0
 */
package org.thingml.xtext.thingML.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import org.thingml.xtext.thingML.MessageParameter;
import org.thingml.xtext.thingML.ThingMLFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Message Parameter</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class MessageParameterTest extends TestCase {

	/**
	 * The fixture for this Message Parameter test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MessageParameter fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(MessageParameterTest.class);
	}

	/**
	 * Constructs a new Message Parameter test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public MessageParameterTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Message Parameter test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(MessageParameter fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Message Parameter test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MessageParameter getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(ThingMLFactory.eINSTANCE.createMessageParameter());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //MessageParameterTest
