/*
 * generated by Xtext 2.38.0
 */
package org.thingml.xtext.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link ThingMLWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractThingMLWebModule extends DefaultWebModule {

}
