package org.thingml.xtext.web;

import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.TimeUnit;

/**
 * Streams preprocessing plots (PNG) generated by a Python helper.
 *
 * Clients should POST JSON:
 * {
 *   "dataset": "my.csv",
 *   "plotType": "LINE_PLOT",
 *   "timestamp": "ON"
 * }
 *
 * Backward compatible keys:
 * - plotType can also be provided in "Preprocessing_Plots"
 */
@WebServlet(name = "PreprocessingPlotServlet", urlPatterns = "/generate-preprocessing-plot")
public class PreprocessingPlotServlet extends HttpServlet {

    private static final int BASE_PORT  = 9200;
    private static final int PORT_RANGE = 200; // 9200-9399

    // If UI sends a wrong plot type (e.g., FORECAST_ERROR), we fallback to this preprocessing plot:
    private static final String DEFAULT_PREPROCESSING_PLOT = "LINE_PLOT";

    // ONLY preprocessing plot types are allowed here.
    private static final Set<String> PREPROCESSING_PLOTS = Set.of(
            "LINE_PLOT",
            "HISTOGRAM",
            "BOX_PLOT",
            "SCATTER_PLOT",
            "HEAT_MAP",
            "AUTOCORRELATION_PLOT",
            "LAG_PLOT",
            "VIOLIN_PLOT",
            "CORRELATION_MATRIX_PLOT",
            "PAIR_PLOT",
            "CLASS_IMBALANCE",
            "MULTIVARIATE_DISTRIBUTION"
    );

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        // 1) Auth
        String userID = (String) request.getSession().getAttribute("userID");
        if (userID == null || userID.isBlank()) {
            plainError(response, HttpServletResponse.SC_UNAUTHORIZED,
                    "Unauthorized: User not logged in (session userID missing).");
            return;
        }

        // 2) Read raw body FIRST (debug + prevents weird reader consumption issues)
        String rawBody = readAll(request);
        System.out.println("[PRE] Raw request body:\n" + rawBody);

        // 3) Parse JSON safely
        Map<String, Object> body;
        try {
            ObjectMapper mapper = new ObjectMapper();
            if (rawBody == null || rawBody.isBlank()) {
                plainError(response, HttpServletResponse.SC_BAD_REQUEST,
                        "Empty request body. Send JSON like {\"dataset\":\"x.csv\",\"plotType\":\"LINE_PLOT\"}.");
                return;
            }
            body = mapper.readValue(rawBody, Map.class);
        } catch (Exception ex) {
            plainError(response, HttpServletResponse.SC_BAD_REQUEST,
                    "Bad JSON body.\n\nRaw:\n" + rawBody + "\n\nError: " + ex);
            return;
        }

        // 4) Extract fields (support many keys)
        String datasetName = firstNonBlank(
                asString(body.get("dataset")),
                asString(body.get("datasetName"))
        );

        String plotType = firstNonBlank(
                asString(body.get("plotType")),
                asString(body.get("Preprocessing_Plots")), // old UI key
                asString(body.get("PreprocessingPlots"))   // just-in-case
        );

        String timestampOption = firstNonBlank(
                asString(body.get("timestamp")),
                "ON"
        );

        System.out.println("[PRE] Parsed dataset=" + datasetName + " plotType=" + plotType + " timestamp=" + timestampOption);

        if (datasetName == null || plotType == null) {
            plainError(response, HttpServletResponse.SC_BAD_REQUEST,
                    "Missing dataset or plot type.\n" +
                    "Parsed dataset=" + datasetName + ", plotType=" + plotType + "\n\n" +
                    "Raw:\n" + rawBody);
            return;
        }

        // Prevent path traversal: keep only filename
        datasetName = Path.of(datasetName).getFileName().toString();

        String originalPlotType = plotType;
        plotType = plotType.toUpperCase();

        // 4.1) Enforce preprocessing plot group with fallback
        boolean fallbackUsed = false;
        if (!PREPROCESSING_PLOTS.contains(plotType)) {
            fallbackUsed = true;
            plotType = DEFAULT_PREPROCESSING_PLOT;
        }

        // Add debug headers
        response.setHeader("X-Original-PlotType", originalPlotType);
        response.setHeader("X-Effective-PlotType", plotType);
        response.setHeader("X-Fallback-Used", String.valueOf(fallbackUsed));

        // 5) Paths
        String rootDir   = "/home/mlpluspy/appservers/apache-tomcat-10.1.26/webapps/ROOT/";
        String sharedDir = rootDir + "Datasets/";
        String plotDir   = rootDir + "PreprocessingPlots/" + userID + "/";

        File plotDirFile = new File(plotDir);
        if (!plotDirFile.exists() && !plotDirFile.mkdirs()) {
            plainError(response, HttpServletResponse.SC_INTERNAL_SERVER_ERROR,
                    "Could not create plot directory: " + plotDir);
            return;
        }

        File datasetFile = new File(sharedDir + datasetName);
        if (!datasetFile.exists() || !datasetFile.isFile()) {
            plainError(response, HttpServletResponse.SC_NOT_FOUND,
                    "Dataset not found at: " + datasetFile.getPath());
            return;
        }

        // Unique and group-specific filename to avoid overwriting by other endpoints
        String safeBase = datasetName.replaceFirst("(?i)\\.csv$", ""); // strips .csv or .CSV
        String plotFileName   = safeBase + "__pre__" + plotType.toLowerCase() + ".png";
        String outputPlotPath = plotDir + plotFileName;

        // 6) Per-user port (kept for compatibility)
        int userPort = BASE_PORT + (Math.abs(userID.hashCode()) % PORT_RANGE);

        // 7) Run python
        RunResult rr = runPython(datasetFile.getPath(), plotType, outputPlotPath, timestampOption, userPort);

        // 8) Decide response
        if (rr.exitCode == 2) {
            plainError(response, HttpServletResponse.SC_BAD_REQUEST,
                    rr.stdout.isBlank() ? "Bad request from python." : rr.stdout);
            return;
        }

        if (rr.exitCode != 0) {
            plainError(response, HttpServletResponse.SC_INTERNAL_SERVER_ERROR,
                    "Plotting failed.\n\nSTDOUT:\n" + rr.stdout);
            return;
        }

        if (rr.noImage) {
            plainError(response, HttpServletResponse.SC_INTERNAL_SERVER_ERROR,
                    "NO_IMAGE from python (unexpected for preprocessing).\n\nSTDOUT:\n" + rr.stdout);
            return;
        }

        // 9) Stream PNG
        Path pngPath = Path.of(outputPlotPath);
        if (!Files.exists(pngPath) || !Files.isRegularFile(pngPath) || Files.size(pngPath) == 0) {
            plainError(response, HttpServletResponse.SC_INTERNAL_SERVER_ERROR,
                    "Python finished but plot file is missing/empty.\nExpected: " + outputPlotPath +
                    "\n\nSTDOUT:\n" + rr.stdout);
            return;
        }

        response.setStatus(HttpServletResponse.SC_OK);
        response.setContentType("image/png");
        response.setHeader("Cache-Control", "no-store");
        response.setHeader("X-Plot-Group", "preprocessing");
        response.setHeader("X-Plot-Path", outputPlotPath);
        response.setContentLengthLong(Files.size(pngPath));

        try (OutputStream out = response.getOutputStream()) {
            Files.copy(pngPath, out);
        }
    }

    // --------------------
    // Helpers
    // --------------------
    private static String readAll(HttpServletRequest req) throws IOException {
        try (var br = req.getReader()) {
            StringBuilder sb = new StringBuilder(1024);
            String line;
            while ((line = br.readLine()) != null) sb.append(line).append('\n');
            return sb.toString().trim();
        }
    }

    private static String asString(Object o) {
        return o == null ? null : String.valueOf(o);
    }

    private static String firstNonBlank(String... vals) {
        if (vals == null) return null;
        for (String v : vals) {
            if (v != null && !v.isBlank()) return v;
        }
        return null;
    }

    private static void plainError(HttpServletResponse resp, int status, String msg) throws IOException {
        resp.resetBuffer(); // avoid Tomcat HTML error pages
        resp.setStatus(status);
        resp.setContentType("text/plain;charset=UTF-8");
        resp.setHeader("Cache-Control", "no-store");
        resp.getWriter().write(msg);
        resp.flushBuffer();
    }

    private static final class RunResult {
        final int exitCode;
        final String stdout;
        final boolean noImage;

        RunResult(int exitCode, String stdout, boolean noImage) {
            this.exitCode = exitCode;
            this.stdout = stdout;
            this.noImage = noImage;
        }
    }

    private RunResult runPython(String datasetPath,
                                String plotType,
                                String outputPlotPath,
                                String timestampOption,
                                int port) {
        try {
            String pythonExe    = "/home/mlpluspy/appservers/apache-tomcat-10.1.26/webapps/ROOT/scripts/venv/bin/python";
            String pythonScript = "/home/mlpluspy/appservers/apache-tomcat-10.1.26/webapps/ROOT/scripts/generate_plot.py";

            ProcessBuilder pb = new ProcessBuilder(
                    pythonExe,
                    pythonScript,
                    datasetPath,
                    plotType,
                    outputPlotPath,
                    timestampOption,
                    String.valueOf(port) // ignored by script; kept for compatibility
            );

            pb.redirectErrorStream(true); // stderr -> stdout
            Process proc = pb.start();

            ByteArrayOutputStream baos = new ByteArrayOutputStream(8_192);
            try (InputStream is = proc.getInputStream()) {
                is.transferTo(baos);
            }

            if (!proc.waitFor(2, TimeUnit.MINUTES)) {
                proc.destroyForcibly();
                return new RunResult(1, "[java] Timeout waiting for python process.", false);
            }

            String stdout = baos.toString(StandardCharsets.UTF_8);
            for (String line : stdout.split("\\R")) System.out.println("[PY] " + line);

            boolean noImage = stdout.contains("NO_IMAGE:");
            return new RunResult(proc.exitValue(), stdout, noImage);

        } catch (Exception e) {
            e.printStackTrace();
            return new RunResult(1, "[java] Exception: " + e, false);
        }
    }
}
